### ISSUE TITLE
Dingo API is not working

### ISSUE THREAD

**Issue by tankhit** [dingo/api#1028]
I have installed laravel 5.1.*,5.0.* and 5.2.*. , dingo api 1.0.x@dev and I have following configuration as per git laravel dingo api.

but I have getting issue once run dingo.

```json
{
message: "404 Not Found",
status_code: 404,
debug: {
line: 161,
file: "/var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php",
class: "Symfony\Component\HttpKernel\Exception\NotFoundHttpException",
trace: [
"#0 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\Routing\RouteCollection->match(Object(Dingo\Api\Http\Request))",
"#1 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\Routing\Router->findRoute(Object(Dingo\Api\Http\Request))",
"#2 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))",
"#3 /var/www/html/karconnect_new_api/vendor/dingo/api/src/Routing/Adapter/Laravel.php(82): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
"#4 /var/www/html/karconnect_new_api/vendor/dingo/api/src/Routing/Router.php(574): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')",
"#5 /var/www/html/karconnect_new_api/vendor/dingo/api/src/Http/Middleware/Request.php(123): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
"#6 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))",
"#7 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
"#8 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#9 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
"#10 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#11 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#12 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
"#13 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#14 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#15 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
"#16 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#17 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#18 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
"#19 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#20 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#21 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
"#22 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#23 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#24 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
"#25 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#27 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
"#28 /var/www/html/karconnect_new_api/vendor/dingo/api/src/Http/Middleware/Request.php(124): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
"#29 /var/www/html/karconnect_new_api/vendor/dingo/api/src/Http/Middleware/Request.php(100): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))",
"#30 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))",
"#31 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))",
"#33 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
"#34 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
"#35 /var/www/html/karconnect_new_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))",
"#36 /var/www/html/karconnect_new_api/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))",
"#37 {main}"
]
}
}
```

please anyone can help for same issue.

**Comment by tisOO** [comment]
Do you have some url like this: "someUrl:somePort/something" ?

**Comment by jasonlewis** [comment]
Not seeing any configuration and that stack doesn't help as it's a plain old not found stack.

If you're still having issues let us know. And post your configuration and what steps you've taken to hit an endpoint.

**Comment by tankhit** [comment]
Sure, 

I have follow instruction from https://github.com/dingo/api/wiki/Installation.

Step 1 :  setting 'API_PREFIX=api' in .env  file

Step 2 : configuration in api.php is following : 
            
              'standardsTree' => env('API_STANDARDS_TREE', 'vnd'),
              'subtype' => env('API_SUBTYPE', ''),
              'version' => env('API_VERSION', 'v1'),
              'prefix' => env('API_PREFIX', 'api'),
              'domain' => env('API_DOMAIN', 'http://localhost/karconnect_new_api'),
              'name' => env('API_NAME', null),
              'conditionalRequest' => env('API_CONDITIONAL_REQUEST', true),
              'strict' => env('API_STRICT', false),
              'debug' => env('API_DEBUG', true),
Step 3: I have written code in route.php file
           
                 $api = app('Dingo\Api\Routing\Router');
                   $api->version('v1', function ($api) {
                             $api->get('/users', function(){
                                 return 'tsdasd';
                            });
                    });
                  
Can you please help for same, where I'm wrong ?

**Comment by enasellithy** [comment]
hi i have same problem i did all steps you're write it but i have still problem i use laravel 5.4
