### ISSUE TITLE
[Laravel 5.2.38] api:docs fails - ReflectionClass

### ISSUE THREAD

**Issue by pionl** [dingo/api#1061]
Hi,

the latest version crashes on generating the API. Using only single controller.

Thank you for this package, great work 👍 

--- 

Exception:
```
#0 /../api/vendor/phpdocumentor/reflection-docblock/src/DocBlock.php(60): Webmozart\Assert\Assert::string(Object(ReflectionClass))
#1 /../api/vendor/drmyersii/dingo-blueprint/src/Resource.php(144): phpDocumentor\Reflection\DocBlock->__construct(Object(ReflectionClass))
#2 /../api/vendor/drmyersii/dingo-blueprint/src/Blueprint.php(145): Dingo\Blueprint\Resource->getDescription()
#3 /../api/vendor/laravel/framework/src/Illuminate/Support/Collection.php(146): Dingo\Blueprint\Blueprint->Dingo\Blueprint\{closure}(Object(Dingo\Blueprint\Resource), 'App\\Api\\Control...')
```

Controller

```
/**
 * Class TokenController
 *
 * @Resource("Auth", uri="/auth")
 * @package App\Api\Controllers\v1\Auth
 */
class TokenController extends Controller
{
    /**
     * Returns the access token
     *
     * @Post("/access_token")
     * @return \Illuminate\Http\JsonResponse
     */
    public function access()
    {
        return Response::json(Authorizer::issueAccessToken());
    }

    /**
     * Rogets the user and the access token
     */
    public function forget()
    {
        
    }
}
```

**Comment by pionl** [comment]
Sorry for issue, probably problem with the hotfix that enables the Laravel 5.2.38 (using drmyersii/dingo-api fork)
