### ISSUE TITLE
[API:docs] error: Fatal error: Class 'App\Api\V1\Requests\Request' not found

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#1112]
Hey,

when I run `php artisan api:docs --output-file docs.md` I get tge following error:

```
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Class 'App\Api\V1\Requests\Request' not found
```

In lumen.log I have:

```
Symfony\Component\Debug\Exception\FatalThrowableError: 
Fatal error: Class 'App\Api\V1\Requests\Request' not found in .../app/Api/V1/Controllers/Controller.php:79
```

**At this line a Rqeuest class is called. But the name is generated depending on the controller that is currently called. Could that be the problem?**

**This is my stack trace, just in case it helps:**

```
Stack trace:
#0 /Users/lukasoppermann/Code/formandsystem-api/app/Api/V1/Controllers/Controller.php(47): App\Api\V1\Controllers\Controller->newRequest(Object(Illuminate\Http\Request))
#1 [internal function]: App\Api\V1\Controllers\Controller->__construct(Object(Illuminate\Http\Request))
#2 /Users/lukasoppermann/Code/formandsystem-api/vendor/illuminate/container/Container.php(783): ReflectionClass->newInstanceArgs(Array)
#3 /Users/lukasoppermann/Code/formandsystem-api/vendor/illuminate/container/Container.php(633): Illuminate\Container\Container->build('App\\Api\\V1\\Cont...', Array)
#4 /Users/lukasoppermann/Code/formandsystem-api/vendor/laravel/lumen-framework/src/Application.php(205): Illuminate\Container\Container->make('App\\Api\\V1\\Cont...', Array)
#5 /Users/lukasoppermann/Code/formandsystem-api/vendor/dingo/api/src/Routing/Route.php(325): Laravel\Lumen\Application->make('App\\Api\\V1\\Cont...')
#6 /Users/lukasoppermann/Code/formandsystem-api/vendor/dingo/api/src/Routing/Route.php(186): Dingo\Api\Routing\Route->makeControllerInstance()
#7 /Users/lukasoppermann/Code/formandsystem-api/vendor/dingo/api/src/Routing/Route.php(167): Dingo\Api\Routing\Route->mergeControllerProperties()
#8 /Users/lukasoppermann/Code/formandsystem-api/vendor/dingo/api/src/Routing/Route.php(144): Dingo\Api\Routing\Route->setupRouteProperties(Object(Illuminate\Http\Request), Array)
#9 /Users/lukasoppermann/Code/formandsystem-api/vendor/dingo/api/src/Routing/Router.php(713): Dingo\Api\Routing\Route->__construct(Object(Dingo\Api\Routing\Adapter\Lumen), Object(Laravel\Lumen\Application), Object(Illuminate\Http\Request), Array)
#10 /Users/lukasoppermann/Code/formandsystem-api/vendor/dingo/api/src/Routing/Router.php(775): Dingo\Api\Routing\Router->createRoute(Array)
#11 /Users/lukasoppermann/Code/formandsystem-api/vendor/dingo/api/src/Console/Command/Docs.php(162): Dingo\Api\Routing\Router->getRoutes()
#12 /Users/lukasoppermann/Code/formandsystem-api/vendor/dingo/api/src/Console/Command/Docs.php(96): Dingo\Api\Console\Command\Docs->getControllers()
#13 [internal function]: Dingo\Api\Console\Command\Docs->handle()
#14 /Users/lukasoppermann/Code/formandsystem-api/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#15 /Users/lukasoppermann/Code/formandsystem-api/vendor/illuminate/console/Command.php(169): Illuminate\Container\Container->call(Array)
#16 /Users/lukasoppermann/Code/formandsystem-api/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/lukasoppermann/Code/formandsystem-api/vendor/illuminate/console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/lukasoppermann/Code/formandsystem-api/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/lukasoppermann/Code/formandsystem-api/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Dingo\Api\Console\Command\Docs), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/lukasoppermann/Code/formandsystem-api/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/lukasoppermann/Code/formandsystem-api/vendor/laravel/lumen-framework/src/Console/Kernel.php(69): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/lukasoppermann/Code/formandsystem-api/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main} 
```

**Comment by hskrasek** [comment]
@lukasoppermann You still having issues with this?

**Comment by lukasoppermann** [comment]
No, now I get the following:

```
lukasoppermann ~/code/dingo-api [master] ❯ php artisan api:docs --output-file docs.md -vvv


  [ErrorException]
  Undefined variable: method


Exception trace:
 () at /Users/lukasoppermann/Code/dingo-api/vendor/dingo/api/src/Routing/Adapter/Lumen.php:267
 Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}() at /Users/lukasoppermann/Code/dingo-api/vendor/dingo/api/src/Routing/Adapter/Lumen.php:267
 Dingo\Api\Routing\Adapter\Lumen->getIterableRoutes() at /Users/lukasoppermann/Code/dingo-api/vendor/dingo/api/src/Routing/Router.php:746
 Dingo\Api\Routing\Router->getRoutes() at /Users/lukasoppermann/Code/dingo-api/vendor/dingo/api/src/Console/Command/Docs.php:151
 Dingo\Api\Console\Command\Docs->getControllers() at /Users/lukasoppermann/Code/dingo-api/vendor/dingo/api/src/Console/Command/Docs.php:95
 Dingo\Api\Console\Command\Docs->handle() at n/a:n/a
 call_user_func_array() at /Users/lukasoppermann/Code/dingo-api/vendor/illuminate/container/Container.php:507
 Illuminate\Container\Container->call() at /Users/lukasoppermann/Code/dingo-api/vendor/illuminate/console/Command.php:169
 Illuminate\Console\Command->execute() at /Users/lukasoppermann/Code/dingo-api/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /Users/lukasoppermann/Code/dingo-api/vendor/illuminate/console/Command.php:155
 Illuminate\Console\Command->run() at /Users/lukasoppermann/Code/dingo-api/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at /Users/lukasoppermann/Code/dingo-api/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /Users/lukasoppermann/Code/dingo-api/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /Users/lukasoppermann/Code/dingo-api/vendor/laravel/lumen-framework/src/Console/Kernel.php:76
 Laravel\Lumen\Console\Kernel->handle() at /Users/lukasoppermann/Code/dingo-api/artisan:35
```

**Comment by hskrasek** [comment]
@lukasoppermann Do you have a small example you could give me to try and re-create this?

**Comment by lukasoppermann** [comment]
Not really, not really, its a huge thingy. I tried creating a new project to see, but I am getting the error, that dingo requires laravel 5.1.

**Comment by hskrasek** [comment]
@lukasoppermann Shouldn't need Laravel 5.1, package dependencies are setup for both 5.1 and 5.2. Are you just doing Laravel, dingo/api and dingo/blueprint?

**Comment by lukasoppermann** [comment]
I installed Lumen and tried to run `composer require dingo/api:1.0.x@dev` which gives me the following output:

```
composer require dingo/api:1.0.x@dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dingo/api v1.0.0-beta5 requires dingo/blueprint 0.2.* -> satisfiable by dingo/blueprint[0.2.x-dev] but these conflict with your requirements or minimum-stability.
    - dingo/api v1.0.0-beta4 requires dingo/blueprint 0.2.* -> satisfiable by dingo/blueprint[0.2.x-dev] but these conflict with your requirements or minimum-stability.
    - dingo/api 1.0.x-dev requires dingo/blueprint 0.2.* -> satisfiable by dingo/blueprint[0.2.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: don't install dingo/api v1.0.0-beta3
    - Conclusion: don't install dingo/api v1.0.0-beta2
    - Installation request for phpdocumentor/reflection-docblock (locked at 3.1.0) -> satisfiable by phpdocumentor/reflection-docblock[3.1.0].
    - Conclusion: remove illuminate/container v5.2.43
    - Installation request for dingo/api 1.0.x@dev -> satisfiable by dingo/api[1.0.x-dev, v1.0.0-beta1, v1.0.0-beta2, v1.0.0-beta3, v1.0.0-beta4, v1.0.0-beta5].
    - Conclusion: don't install illuminate/container v5.2.43
    - dingo/api v1.0.0-beta1 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.1 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.13 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.16 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.2 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.20 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.22 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.25 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.28 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.30 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.31 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.41 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.6 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/routing v5.1.8 requires illuminate/container 5.1.* -> satisfiable by illuminate/container[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - Can only install one of: illuminate/container[v5.1.1, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.13, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.16, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.2, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.20, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.22, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.25, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.28, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.30, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.31, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.41, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.6, v5.2.43].
    - Can only install one of: illuminate/container[v5.1.8, v5.2.43].
    - Installation request for illuminate/container (locked at v5.2.43) -> satisfiable by illuminate/container[v5.2.43].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by hskrasek** [comment]
@lukasoppermann I don't fully understand what composer is doing here, but if you add `"minimum-stability": "dev"` to your composer file and then run the above `composer require`, it'll install just fine.

**Comment by hskrasek** [comment]
Related #1163

**Comment by hskrasek** [comment]
@lukasoppermann Is this issue still happening?
