### ISSUE TITLE
invalid argument exception

### ISSUE THREAD

**Issue by adulion** [dingo/api#1124]
i tried running php artisan api:routes and i was getting the following error. I commented out the offending line the package just to get it working but its not going to fly when we push to deployment. i'm on 1.0.0-beta3

```
[2016-07-19 15:10:52] local.ERROR: exception 'InvalidArgumentException' with message 'The "reverse" option does not exist.' in /Users/adulion/Documents/php/apilv5/vendor/symfony/console/Input/Input.php:154
Stack trace:
#0 /Users/adulion/Documents/php/apilv5/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Symfony\Component\Console\Input\Input->getOption('reverse')
#1 /Users/adulion/Documents/php/apilv5/vendor/dingo/api/src/Console/Command/Routes.php(88): Illuminate\Console\Command->option('reverse')
#2 /Users/adulion/Documents/php/apilv5/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(74): Dingo\Api\Console\Command\Routes->getRoutes()
#3 [internal function]: Illuminate\Foundation\Console\RouteListCommand->fire()
#4 /Users/adulion/Documents/php/apilv5/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#5 /Users/adulion/Documents/php/apilv5/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#6 /Users/adulion/Documents/php/apilv5/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/adulion/Documents/php/apilv5/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/adulion/Documents/php/apilv5/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/adulion/Documents/php/apilv5/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Dingo\Api\Console\Command\Routes), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/adulion/Documents/php/apilv5/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/adulion/Documents/php/apilv5/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/adulion/Documents/php/apilv5/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}  
```

Here is a screenshot of the offending line being commented out- is it a mistake on my end? i upgraded laravel 5.0 to 5.1 manually which i may have missed something?

![image](https://cloud.githubusercontent.com/assets/667797/16985866/394bfaf6-4e7b-11e6-964e-e8a9beefe832.png)

**Comment by adulion** [comment]
i upgraded to 5.2 and seems to have fixed this-
