### ISSUE TITLE
Base route showing 404

### ISSUE THREAD

**Issue by alexjose** [dingo/api#1233]
I have installed dingo on Lumen 5.3 with _API_PREFIX=/._

I am trying to add a route

``` php
$api->get('/', function () use ($app) {
    return $app->version();
});
```

But I am getting 404 on this route.

Thanks in advance for the help.

**Comment by mg-freelancer** [comment]
I will check that to find solution for this problem

**Comment by hskrasek** [comment]
@alexjose If you don't want a prefix at all, you could just set API_PREFIX to an empty value, or remove it from the env and set API_DOMAIN instead

**Comment by alexjose** [comment]
It is not working even if i set the domain instead of the prefix.

**Comment by intositeme** [comment]
Experiencing the same issues here. Tried with a bare Laravel 5.3 installation & get the same error.

**Comment by alexjose** [comment]
@mg-freelancer Did you get a chance to look into it?

**Comment by jasonlewis** [comment]
Is it a JSON 404, like this:

```json
{"message":"404 Not Found", "status_code":404}
```

**Comment by alexjose** [comment]
@jasonlewis Yes. same output.

**Comment by jasonlewis** [comment]
Then it's likely you're hitting the wrong endpoint.

I just spun up a quick Lumen 5.3 install.

Included Dingo: `composer require dingo/api:1.0.x@dev`

Adjusted `.env` file:

```
API_PREFIX=/
```

Adjusted `bootstrap/app.php`:

```php
$app->register(Dingo\Api\Provider\LumenServiceProvider::class);
```

And added a route:

```php
app('api.router')->version('v1', function ($api) {
	$api->get('/', function () {
		return ['version' => app()->version()];
	});
});
```

Running `php -S localhost:8000` within the public folder and I can hit `localhost:8000` in my browser and see the JSON response.

**Comment by alexjose** [comment]
This seems to be working only with php builtin server.  It is showing 404 error f we access the same app using apache as

`http://localhost/dingo/public/`

or apache virtualhost

`http://localhost:9000`.

**Comment by TFarla** [comment]
I'm experiencing the same issue.
I've configured the LumenServiceProvider inside app.php and every endpoint returns a 404.

My .env file:

```sh
APP_ENV=local
APP_DEBUG=true
API_DEBUG=true
APP_KEY=
APP_TIMEZONE=UTC

API_STANDARDS_TREE=vnd
API_SUBTYPE=todos
API_PREFIX=todo
API_VERSION=v1
API_NAME="My API"

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

CACHE_DRIVER=memcached
QUEUE_DRIVER=sync
```

routes.php:

```php
<?php
use Dingo\Api\Routing\Router;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/

/** @var \Dingo\Api\Routing\Router $api */
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function(Router $api){
    $api->get('collections/{collection}', function(){
        return 'test';
    });
});

return $api;
```

When I navigate to /todo/v1/collection/1 I receive a 404:

```js
{"message":"404 Not Found","status_code":404,"debug":{"line":594,"file":"\/home\/vagrant\/dingo\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":["#0 \/home\/vagrant\/dingo\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(532): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#1 \/home\/vagrant\/dingo\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(781): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()","#2 \/home\/vagrant\/dingo\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(534): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#3 \/home\/vagrant\/dingo\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))","#4 \/home\/vagrant\/dingo\/vendor\/dingo\/api\/src\/Routing\/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#5 \/home\/vagrant\/dingo\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#6 \/home\/vagrant\/dingo\/vendor\/illuminate\/pipeline\/Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#7 \/home\/vagrant\/dingo\/vendor\/illuminate\/pipeline\/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#8 \/home\/vagrant\/dingo\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#9 \/home\/vagrant\/dingo\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#10 \/home\/vagrant\/dingo\/vendor\/illuminate\/pipeline\/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#11 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#12 \/home\/vagrant\/dingo\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#13 \/home\/vagrant\/dingo\/vendor\/illuminate\/pipeline\/Pipeline.php(102): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#14 \/home\/vagrant\/dingo\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(778): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#15 \/home\/vagrant\/dingo\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(534): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#16 \/home\/vagrant\/dingo\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(475): Laravel\\Lumen\\Application->dispatch(NULL)","#17 \/home\/vagrant\/dingo\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#18 {main}"]}}
```

**Comment by stygiansabyss** [comment]
Also getting the 404 (suddenly.  This was not happening before)

**Comment by jayaryan** [comment]
@TFarla try by removing v1 from the url

**Comment by skipperstrange** [comment]
I'm also battling with this
