### ISSUE TITLE
FatalThrowableError: Call to undefined method Dingo\Api\Auth\Auth::handle() in Laravel 5.4

### ISSUE THREAD

**Issue by gitstashgithub** [dingo/api#1333]
```
[2017-02-10 13:13:49] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Dingo\Api\Auth\Auth::handle() in /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:148
Stack trace:
#0 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#1 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#2 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#3 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))
#4 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))
#5 /home/vagrant/projects/myproject/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#6 /home/vagrant/projects/myproject/vendor/dingo/api/src/Routing/Router.php(559): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')
#7 /home/vagrant/projects/myproject/vendor/dingo/api/src/Http/Middleware/Request.php(112): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#8 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))
#9 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#10 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#11 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#12 /home/vagrant/projects/myproject/vendor/dingo/api/src/Http/Middleware/Request.php(113): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/vagrant/projects/myproject/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))
#14 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Dingo\Api\Http\Middleware\Request->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#15 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#19 /home/vagrant/projects/myproject/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#20 {main}  
[2017-02-10 13:13:49] local.ERROR: InvalidArgumentException: Attribute [gatherRouteMiddlewares] does not exist. in /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php:75
Stack trace:
#0 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1085): Illuminate\Routing\RouteRegistrar->attribute('gatherRouteMidd...', Object(Illuminate\Routing\Route))
#1 /home/vagrant/projects/myproject/vendor/dingo/api/src/Routing/Adapter/Laravel.php(197): Illuminate\Routing\Router->__call('gatherRouteMidd...', Array)
#2 /home/vagrant/projects/myproject/vendor/dingo/api/src/Routing/Router.php(626): Dingo\Api\Routing\Adapter\Laravel->gatherRouteMiddlewares(Object(Illuminate\Routing\Route))
#3 /home/vagrant/projects/myproject/vendor/dingo/api/src/Http/Middleware/Request.php(182): Dingo\Api\Routing\Router->gatherRouteMiddlewares(Object(Illuminate\Routing\Route))
#4 /home/vagrant/projects/myproject/vendor/dingo/api/src/Http/Middleware/Request.php(131): Dingo\Api\Http\Middleware\Request->gatherRouteMiddlewares(Object(Dingo\Api\Http\Request))
#5 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(216): Dingo\Api\Http\Middleware\Request->terminate(Object(Dingo\Api\Http\Request), Object(Dingo\Api\Http\Response))
#6 /home/vagrant/projects/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(187): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Dingo\Api\Http\Response))
#7 /home/vagrant/projects/myproject/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Dingo\Api\Http\Response))
#8 {main}  
```
Thanks!

**Comment by gg444108853** [comment]
I also get a same problem.
