### ISSUE TITLE
laravel5.1 Class api.router does not exist 

### ISSUE THREAD

**Issue by xiexiangnow** [dingo/api#1361]
config/app.php:
Dingo\Api\Provider\LaravelServiceProvider::class,
web show this error:
  ReflectionException in Container.php line 741:
  Class api.router does not exist

and，composer update is show Class api.router does not exist

I don't know what's wrong，Thanks in advance！

**Comment by manuel-burato** [comment]
Similar error here.
`php artisan serve` output:
```
  [ReflectionException]        
  Class router does not exist
```
same thing updating or installing dependecies with composer.

here's laravel logs for that error:
```
[2017-04-07 13:12:25] local.ERROR: exception 'ReflectionException' with message 'Class router does not exist' in {{appDir}}/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
Stack trace:
#0 {{appDir}}/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('router')
#1 {{appDir}}/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('router', Array)
#2 {{appDir}}/vendor/whitebizon/laravel5/src/Irradiate/Foundation/Application.php(687): Illuminate\Container\Container->make('router', Array)
#3 {{appDir}}/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Irradiate\Foundation\Application->make('Illuminate\\Rout...')
#4 {{appDir}}/vendor/laravel/framework/src/Illuminate/Container/Container.php(532): Illuminate\Container\Container->addDependencyForCallParameter(Object(ReflectionParameter), Array, Array)
#5 {{appDir}}/vendor/laravel/framework/src/Illuminate/Container/Container.php(500): Illuminate\Container\Container->getMethodDependencies(Array, Array)
#6 {{appDir}}/vendor/whitebizon/laravel5/src/Irradiate/Foundation/Application.php(748): Illuminate\Container\Container->call(Array)
#7 {{appDir}}/vendor/whitebizon/laravel5/src/Irradiate/Foundation/Application.php(730): Irradiate\Foundation\Application->bootProvider(Object(MEM\Providers\RouteServiceProvider))
#8 [internal function]: Irradiate\Foundation\Application->Irradiate\Foundation\{closure}(Object(MEM\Providers\RouteServiceProvider), 'MEM\\Providers\\R...')
#9 {{appDir}}/vendor/whitebizon/laravel5/src/Irradiate/Foundation/Application.php(731): array_walk(Array, Object(Closure))
#10 {{appDir}}/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Irradiate\Foundation\Application->boot()
#11 {{appDir}}/vendor/whitebizon/laravel5/src/Irradiate/Foundation/Application.php(204): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Irradiate\Foundation\Application))
#12 {{appDir}}/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(206): Irradiate\Foundation\Application->bootstrapWith(Array)
#13 {{appDir}}/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(98): Illuminate\Foundation\Console\Kernel->bootstrap()
#14 {{appDir}}/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}  
```

**Comment by tsurumure** [comment]
/bootstrap/cache/routes.php
Delete **app('api.router')->**
Hope to help you:)
