### ISSUE TITLE
Api routes can't be accessed even they are listed in api:routes

### ISSUE THREAD

**Issue by lear2012** [dingo/api#1466]
| Q                 | A
| Api routes can't be accessed even they are listed in api:routes
| Bug?              | not sure
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4
| Package version   | 1.0.*@dev
| PHP version       | 5.6

#### Actual Behaviour

when i use api:routes to list all the api routes in console, the routes are all there, the question is 
that some routes can be access and return the expected data while others can't be accessed and return something like
{"message":"404 Not Found","status_code":404,"debug":{"line":179,"file":"\/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/RouteCollection.php","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":["#0 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(546): Illuminate\\Routing\\RouteCollection->match(Object(Dingo\\Api\\Http\\Request))","#1 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(525): Illuminate\\Routing\\Router->findRoute(Object(Dingo\\Api\\Http\\Request))","#2 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(511): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))","#3 \/Users\/liaolliso\/work\/laravel54\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#4 \/Users\/liaolliso\/work\/laravel54\/vendor\/dingo\/api\/src\/Routing\/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#5 \/Users\/liaolliso\/work\/laravel54\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#6 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#7 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#8 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#9 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#10 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#11 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#12 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#13 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#14 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#15 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#16 \/Users\/liaolliso\/work\/laravel54\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#17 \/Users\/liaolliso\/work\/laravel54\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#18 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))","#19 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#20 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#21 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#22 \/Users\/liaolliso\/work\/laravel54\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))","#23 \/Users\/liaolliso\/work\/laravel54\/public\/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))","#24 {main}"]}}

The difference is that:
$api->get('keye_route/{id}', ['as' => 'keye_route.get', 'uses' => 'KeyeRouteController@get'])->where('id', '[0-9]+'); // can be accessed, example: /api/keye_route/1232131231
$api->get('keye_routes/get_by_tag', ['as' => 'keye_route.get_by_tag', 'uses' => 'KeyeRouteController@getTagRoutes']);  // can't be accessed, example: /api/keye_route/get_by_tag?tag=aaa&page=1
In controller i use $id for the first route to get params while i use Request $request to get the params in second route.

More: i can access them some days ago while i can't now even without any touch to the code.  I wonder if it's because of composer update which i did recently, im not sure. 
Hope someone could help. Thanks

#### Expected Behaviour

api routes could be access like other routes

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by lear2012** [comment]
idiot i am.... lose a s in the route
