### ISSUE TITLE
All Dingo routes return 404 when phpunit testing

### ISSUE THREAD

**Issue by UniFreak** [dingo/api#1472]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.1
| Package version   | 1.0.x
| PHP version       | 7.x.y

Firstly, I already checked three issues regarding to routes problem under phpunit testing enviroment, and I think that this issue might requires some documentation update, for they are so common and annoying.

Here is a simplified routes definition in `app\Http\routes.php`:

```php
$app->get('/', function () use ($app) {
    return "Welcome to mysite.com";
});

$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {
    $api->group([
        'prefix' => 'dealer',
        'middleware' => 'checkH5ApiSign'
    ], function ($api) {
        $api->get('list', 'App\Http\Controllers\Credit\DealerController@index');
        $api->get('staff_list', 'App\Http\Controllers\Credit\DealerController@getStaffList');
    });
}
```

I can access both routes defined using `$app` or `$api`(dingo) in browser or via postman, they both can return a 200 response. But whenever I'm trying to access those routes in phpunit, the `$app` defined route like `/` is responding okay with 200 code, but all routes defined with `$api`(dingo) will response with 404 status code. Here is my test code and ran result:

```php
class DealerTest extends TestCase
{
    public function testTest()
    {

        $this->get('/')->assertResponseOk();
        $this->get('/dealer/list')->assertResponseOk();
        $this->get('/dealer/staff_list')->assertResponseOk();
    }
}
```

```bash
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

F                                                                  1 / 1 (100%)

Time: 590 ms, Memory: 6.00MB

There was 1 failure:

1) DealerTest::testTest
Expected status code 200, got 404.
Failed asserting that false is true.

E:\Gitrepos\api.fin.youxinjinrong.com\vendor\laravel\lumen-framework\src\Testing\AssertionsTrait.php:19
E:\Gitrepos\api.fin.youxinjinrong.com\tests\DealerTest.php:8

FAILURES!
Tests: 1, Assertions: 2, Failures: 1.
```

I tried  ran through Dingo package code to find the cause, but failed. All other related issue could not solve my problem either. So please help me.

#### update:

I followed the code flow, and see that `FastRoute\DataGenerator\RegexBasedAbstract.php` is doing the `addRoute()` operation, I dumped `$this->staticRoutes)` in that `addRoute()` method, see that it's doing okay both inside browser and under phpunit. But  weird enough, the following call of `->getData()` is behaving differenctly: in browser all static routes are returned, but not in phpunit.

Hope this can somehow be helpful. I'm still digging this problem...

**Comment by from2day** [comment]
Hi,

have you set the header to specify api versioning. Or try to check the configuration part regarding dingo api base url, default versioning.
Sounds like misconfiguration between the environments. Maybe test env differs somehow?

**Comment by byrnedo** [comment]
@UniFreak you ever get around this problem?

**Comment by neoighodaro** [comment]
Did you try setting the correct `APP_URL` in `phpunit.xml` ?

**Comment by byrnedo** [comment]
Yeah @neoighodaro , it was my APP_URL that somehow started getting honored between updating our project from 5.3 to 5.5

**Comment by UniFreak** [comment]
@neoighodaro I tried and verified that the `APP_URL` in `phpunit.xml` is the same with my `.env` file. But no, still 404. I also tried change the `bootstrap`'s value to `public/index.php`, still 404. Here is what error trace I got: 

```
{
"message": "404 Not Found",
"status_code": 404,
"debug": {
"line": 1264,
"file": "E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\laravel\\lumen-framework\\src\\Application.php",
"class": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
"trace": [
"#0 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\laravel\\lumen-framework\\src\\Application.php(1219): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)",
"#1 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\laravel\\lumen-framework\\src\\Application.php(1454): Laravel\\Lumen\\Application->Laravel\\Lumen\\{closure}()",
"#2 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\laravel\\lumen-framework\\src\\Application.php(1221): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
"#3 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))",
"#4 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\dingo\\api\\src\\Routing\\Router.php(513): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
"#5 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
"#6 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#7 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\illuminate\\pipeline\\Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
"#8 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#9 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\illuminate\\pipeline\\Pipeline.php(102): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
"#10 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
"#11 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
"#12 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#13 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\illuminate\\pipeline\\Pipeline.php(124): call_user_func_array(Array, Array)",
"#14 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
"#15 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\illuminate\\pipeline\\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
"#16 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\laravel\\lumen-framework\\src\\Application.php(1451): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
"#17 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\laravel\\lumen-framework\\src\\Application.php(1221): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
"#18 E:\\Gitrepos\\api.fin.youxinjinrong.com\\vendor\\laravel\\lumen-framework\\src\\Application.php(1161): Laravel\\Lumen\\Application->dispatch(NULL)",
"#19 E:\\Gitrepos\\api.fin.youxinjinrong.com\\public\\index.php(28): Laravel\\Lumen\\Application->run()",
"#20 phar://C:/cygwin64/bin/phpunit/phpunit/Util/Fileloader.php(56): include_once('E:\\\\Gitrepos\\\\api...')",
"#21 phar://C:/cygwin64/bin/phpunit/phpunit/Util/Fileloader.php(38): PHPUnit_Util_Fileloader::load('E:\\\\Gitrepos\\\\api...')",
"#22 phar://C:/cygwin64/bin/phpunit/phpunit/TextUI/Command.php(913): PHPUnit_Util_Fileloader::checkAndLoad('E:\\\\Gitrepos\\\\api...')",
"#23 phar://C:/cygwin64/bin/phpunit/phpunit/TextUI/Command.php(738): PHPUnit_TextUI_Command->handleBootstrap('E:\\\\Gitrepos\\\\api...')",
"#24 phar://C:/cygwin64/bin/phpunit/phpunit/TextUI/Command.php(129): PHPUnit_TextUI_Command->handleArguments(Array)",
"#25 phar://C:/cygwin64/bin/phpunit/phpunit/TextUI/Command.php(118): PHPUnit_TextUI_Command->run(Array, true)",
"#26 C:\\cygwin64\\bin\\phpunit(581): PHPUnit_TextUI_Command::main()",
"#27 {main}"
]
}
}
```

I'll paste my phpunit.xml and .env here, hope somebody can figure out the problem.

phpunit.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/app.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory>./tests/</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist>
            <directory suffix=".php">app/</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="local"/>
        <env name="API_DEBUG"  value="true"/>
        <env name="API_KEY"  value="SomeRandomKey!!!"/>
        <env name="APP_LOCALE"  value="en"/>
        <env name="APP_FALLBACK_LOCALE"  value="en"/>
        <env name="API_STANDARDS_TREE"  value="vnd"/>
        <env name="API_DOMAIN"  value="api.fin.youxinjinrong.local/"/>
        <env name="API_URL"  value="api.fin.youxinjinrong.local/"/>
        <env name="API_VERSION"  value="v1"/>
        <env name="API_NAME"  value="credit"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="API_CONDITIONAL_REQUEST"  value="false"/>
        <env name="API_STRICT"  value="false"/>
    </php>
</phpunit>
```

.env:
```
APP_ENV=local
APP_DEBUG=true
APP_KEY=SomeRandomKey!!!

APP_LOCALE=en
APP_FALLBACK_LOCALE=en

CACHE_DRIVER=memcached
SESSION_DRIVER=memcached
QUEUE_DRIVER=database

API_STANDARDS_TREE=vnd
API_DOMAIN=api.fin.youxinjinrong.local
API_VERSION=v1
API_NAME=credit
API_CONDITIONAL_REQUEST=false
API_STRICT=false
API_DEBUG=true
```

**Comment by from2day** [comment]
Have you tried to clear cache and/or config:

- php artisan config:clear
- php arttisan cache:clear

**Comment by UniFreak** [comment]
@from2day 
`php artisan config:clear` gave me:

```
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.
```

`php artisan cache:clear` gave me:

```                                                   
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Memcached' not found        
```

**Comment by from2day** [comment]
@UniFreak Yeah the config:clear is quite new command, so it's not there in Lumen 5.1 and it is irrelevant in your case.

The other one is that you have to set correct cache driver try with file based one: `CACHE_DRIVER=file` in .env file.

**Comment by lucassmacedo** [comment]
i have the same problem

**Comment by laclance** [comment]
me too

**Comment by petersowah** [comment]
Any luck with this issue?

**Comment by petersowah** [comment]
So I got mine to work by doing this;
Using the example in the example used in creating the issue,
`class DealerTest extends TestCase
{
    public function testTest()
    {

        $this->get('/')->assertResponseOk();
        $this->get('/dealer/list')->assertResponseOk();
        $this->get('/dealer/staff_list')->assertResponseOk();
    }
}` becomes 
`class DealerTest extends TestCase
{
    public function testTest()
    {
        $this->get(getenv('API_DOMAIN') . '/v1/')->assertResponseOk();
        $this->get(getenv('API_DOMAIN') . '/v1/dealer/list')->assertResponseOk();
        $this->get('/dealer/staff_list')->assertResponseOk();
    }
}`

**Comment by xwiz** [comment]
In my case the fault was from laravel's `WithoutMiddleware` trait. Remove it and everything works fine, put it back and 404 errors all over. Still trying to figure out how to fix it.

**Comment by xwiz** [comment]
Manually specifying disabling of api.auth middleware leads to `Argument 2 passed to Dingo\Api\Http\Middleware\Auth::__construct() must be an instance of Dingo\Api\Auth\Auth, instance of class@anonymous given`

**Comment by xwiz** [comment]
Finally found the culprit: The package causing all the 404 was `barryvdh/laravel-cors` package registered on the api middleware.

**Comment by specialtactics** [comment]
Closing this due to age, and old dingo version in OP

**Comment by ALTELMA** [comment]
In 2020, I still facing this problem. Any update?

**Comment by specialtactics** [comment]
Hi, there is definitely no problem of this sort, I know because we have tonnes of unit tests involving this project. If you are having a problem, please post a new issue with the correct format and code samples.
