### ISSUE TITLE
ErrorException thrown by Dingo Router

### ISSUE THREAD

**Issue by harhoo** [dingo/api#353]
I've belatedly upgraded from 0.6 to 0.8, and I've started to get the following error in my logs; this doesn't seem to effect the actual site itself or the api, but it is filling up my logs and causing Clockwork to stop working which is making debugging a pain. 

```php
[2015-01-30 10:41:04] local.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, no array or string given' in /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php:109
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'call_user_func_...', '/Users/david/Si...', 109, Array)
#1 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(NULL, Array)
#2 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#3 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#4 /Users/david/Sites/my.site.com/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#5 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /Users/david/Sites/my.site.com/app/MyApp/Service/Http/ApiRights.php(66): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#8 /Users/david/Sites/my.site.com/app/MyApp/Service/Http/ApiLogging.php(69): Logbook\Service\Http\ApiRights->handle(Object(Illuminate\Http\Request), 1, true)
#9 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Logbook\Service\Http\ApiLogging->handle(Object(Illuminate\Http\Request), 1, true)
#10 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#11 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#12 /Users/david/Sites/my.site.com/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#13 /Users/david/Sites/my.site.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#14 /Users/david/Sites/my.site.com/public/index.php(49): Illuminate\Foundation\Application->run()
#15 {main} [] []
```

I don't fully understand the issue, as I can't see what Dingo could be doing to alter the request, but am pretty sure it's 0.8 related (or at least my implementation of the upgrade). If I comment out $this->replaceBoundRouter() in RoutingServiceProvider everything starts working again; if I remove my additional middleware that doesn't make any difference; if I revert back to 0.6 then the errors stop and Clockwork starts working again. One other thing to note is that this error happens if browsing the site, but not if calling the API. (i.e. I have a website at site.com and an api at site.com/api).

Any idea what could be causing this?

**Comment by harhoo** [comment]
And in case it's relevant, my routes are all of the form:

    Route::get('login', 'AuthController@getLogin');

**Comment by harhoo** [comment]
Ah, OK. Apologies. It looks like it was a conflict between Clockwork and Dingo - as part of the upgrade I moved the order of the ServiceProviders around, and as both overwrite routes, that was causing the issue. Moving Clockwork below Dingo in app.php seems to have fixed it again. 

I'll now get back to doing work rather than spending hours commenting out code, dumping things to the screen and searching error messages on Google...
