### ISSUE TITLE
Error when returning Eloquent model directly instead of using $this->response->array()

### ISSUE THREAD

**Issue by gidomanders** [dingo/api#378]
I get an error when trying to respond with the found model. I use Laravel 4.2. Like in the tutorial, the model extends Eloquent\Model and my in controller I have `use ControllerTrait` and `return $item`.

Here's the error:

```
exception 'ErrorException' with message 'Illegal offset type in isset or empty' in /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/Pluralizer.php:155
Stack trace:
#0 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/Pluralizer.php(155): Illuminate\Exception\Handler->handleError(2, 'Illegal offset ...', '/home/vagrant/c...', 155, Array)
#1 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/Str.php(275): Illuminate\Support\Pluralizer::singular(Array)
#2 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/helpers.php(917): Illuminate\Support\Str::singular(Array)
#3 /home/vagrant/code/vendor/dingo/api/src/Http/ResponseFormat/JsonResponseFormat.php(18): str_singular(Array)
#4 /home/vagrant/code/vendor/dingo/api/src/Http/Response.php(68): Dingo\Api\Http\ResponseFormat\JsonResponseFormat->formatEloquentModel(Object(Itern\Talent))
#5 /home/vagrant/code/vendor/dingo/api/src/Routing/Router.php(252): Dingo\Api\Http\Response->morph('json')
#6 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#7 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#8 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#9 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#10 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#11 /home/vagrant/code/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#12 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#13 /home/vagrant/code/public/index.php(49): Illuminate\Foundation\Application->run()
#14 {main} [] []
```

I logged $value before the isset in Pluralizer::singular, which logged an array containing the tablename/classname of the model.

When using `$this->response->array($item)` everything works like a charm, but the tutorial says just returning the object itself is enough, which allows for shorter and more readable code.

**Comment by bweston92** [comment]
Have you tried returning `$item->toArray()` and `dd(get_class($item))` to make sure everything is correct?

**Comment by bweston92** [comment]
I think this error would raise when you're model has an array inside of it self! Check that none of the attributes have array values.

**Comment by gidomanders** [comment]
It worked, thanks!

**Comment by gildniy** [comment]
Yeah this helps me too on Laravel 5. Thanks
