### ISSUE TITLE
Error executing 'php artisan config:publish dingo/api'

### ISSUE THREAD

**Issue by rodrigobendia** [dingo/api#395]
I'm getting the following error when executing **php artisan config:publish dingo/api**:

```
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /laravel/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:226
Stack trace:
#0 /laravel/vendor/dingo/api/src/Provider/ConfigServiceProvider.php(17): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 /laravel/vendor/dingo/api/src/Provider/ConfigServiceProvider.php(17): Dingo\Api\Provider\ConfigServiceProvider->package('dingo/api', 'api', '/laravel/C...')
#2 [internal function]: Dingo\Api\Provider\ConfigServiceProvider->boot()
#3 /laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(703): Illuminate\Container\Container->call(Array)
#5 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(685): Illuminate\Foundation\Application->bootProvider(Object(Dingo\Api\Provider\ConfigServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Dingo\Api\Provider\ConfigServiceProvider), 20)
#7 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): array_walk(Array, Object(Closure))
#8 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#9 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(181): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(92): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /laravel/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
It seems that the **package** method was removed from the **ServiceProvider** in Laravel 5.

**Comment by soonkin** [comment]
This package is not compatible with L5 yet, please take  a look at the Wiki

**Comment by rodrigobendia** [comment]
I know it's not compatible. Just though it would be helpful to make it
compatible...

Em Qui, 30 de abr de 2015 02:17, Soon Ya Kin <notifications@github.com>
escreveu:

**Comment by vinkla** [comment]
@rodrigobendia Please see [Regarding L5: Read before posting an issue!](https://github.com/dingo/api/issues/213).

**Comment by jasonlewis** [comment]
Will work with Laravel 5 now. Use the `vendor:publish` method.
