### ISSUE TITLE
[L5.1] api doesnt seem to be able to resolve from main router

### ISSUE THREAD

**Issue by xLink** [dingo/api#464]
Just got all setup, finished porting my stuff over from the older base, but it looks like the Dingo Router cant resolve routes from the Laravel Router.

Full Stack Trace:
```json
{

    "message": "Route [pxcms.user.view] not defined.",
    "status_code": 500,
    "debug": 

    {

    "line": 276,
    "file": "/Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php",
    "class": "InvalidArgumentException",
    "trace": 

        [
            "#0 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(464): Illuminate\\Routing\\UrlGenerator->route('pxcms.user.view', Array, true, NULL)",
            "#1 /Users/danaldridge/Sites/pxcms/app/Modules/Core/Traits/LinkableTrait.php(45): route('pxcms.user.view', Array)",
            "#2 /Users/danaldridge/Sites/pxcms/app/Modules/Auth/Models/User.php(166): Cms\\Modules\\Core\\Models\\BaseModel->makeLink(true)",
            "#3 /Users/danaldridge/Sites/pxcms/app/Modules/Core/Http/Controllers/Api/v1/PagesController.php(15): Cms\\Modules\\Auth\\Models\\User->transform()",
            "#4 [internal function]: Cms\\Modules\\Core\\Http\\Controllers\\Api\\V1\\PagesController->getUser()",
            "#5 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(255): call_user_func_array(Array, Array)",
            "#6 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(163): Illuminate\\Routing\\Controller->callAction('getUser', Array)",
            "#7 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(111): Illuminate\\Routing\\ControllerDispatcher->call(Object(Cms\\Modules\\Core\\Http\\Controllers\\Api\\V1\\PagesController), Object(Illuminate\\Routing\\Route), 'getUser')",
            "#8 [internal function]: Illuminate\\Routing\\ControllerDispatcher->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#9 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#10 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#11 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#12 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(113): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#13 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\\Routing\\ControllerDispatcher->callWithinStack(Object(Cms\\Modules\\Core\\Http\\Controllers\\Api\\V1\\PagesController), Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request), 'getUser')",
            "#14 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(199): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request), 'Cms\\\\Modules\\\\Cor...', 'getUser')",
            "#15 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(132): Illuminate\\Routing\\Route->runWithCustomDispatcher(Object(Dingo\\Api\\Http\\Request))",
            "#16 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Route->run(Object(Dingo\\Api\\Http\\Request))",
            "#17 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#18 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#19 /Users/danaldridge/Sites/pxcms/vendor/dingo/api/src/Http/Middleware/RateLimit.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#20 [internal function]: Dingo\\Api\\Http\\Middleware\\RateLimit->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#21 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#22 /Users/danaldridge/Sites/pxcms/vendor/dingo/api/src/Http/Middleware/Auth.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#23 [internal function]: Dingo\\Api\\Http\\Middleware\\Auth->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#24 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#25 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#26 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#27 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#28 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
            "#29 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
            "#30 /Users/danaldridge/Sites/pxcms/vendor/dingo/api/src/Routing/Adapter/Laravel.php(58): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#31 /Users/danaldridge/Sites/pxcms/vendor/dingo/api/src/Routing/Router.php(526): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
            "#32 /Users/danaldridge/Sites/pxcms/vendor/dingo/api/src/Http/Middleware/Request.php(91): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#33 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#34 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#35 /Users/danaldridge/Sites/pxcms/app/Modules/Core/Http/Middleware/MinifyHtmlMiddleware.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#36 [internal function]: Cms\\Modules\\Core\\Http\\Middleware\\MinifyHtmlMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#37 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#38 /Users/danaldridge/Sites/pxcms/app/Modules/Core/Http/Middleware/ParseJsToBottomMiddleware.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#39 [internal function]: Cms\\Modules\\Core\\Http\\Middleware\\ParseJsToBottomMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#40 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#41 /Users/danaldridge/Sites/pxcms/app/Modules/Core/Http/Middleware/ForceSecureMiddleware.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#42 [internal function]: Cms\\Modules\\Core\\Http\\Middleware\\ForceSecureMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#43 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#44 /Users/danaldridge/Sites/pxcms/app/Http/Middleware/InMaintenanceMiddleware.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#45 [internal function]: Cms\\Http\\Middleware\\InMaintenanceMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#46 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#47 /Users/danaldridge/Sites/pxcms/app/Http/Middleware/IsInstalledMiddleware.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#48 [internal function]: Cms\\Http\\Middleware\\IsInstalledMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#49 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#50 /Users/danaldridge/Sites/pxcms/app/Http/Middleware/VerifyCsrfToken.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#51 [internal function]: Cms\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#52 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#53 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#54 [internal function]: Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#55 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#56 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#57 [internal function]: Illuminate\\Session\\Middleware\\StartSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#58 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#59 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#60 [internal function]: Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#61 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#62 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#63 [internal function]: Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#64 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#65 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#66 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#67 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#68 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#69 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#70 /Users/danaldridge/Sites/pxcms/vendor/dingo/api/src/Http/Middleware/Request.php(92): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#71 /Users/danaldridge/Sites/pxcms/vendor/dingo/api/src/Http/Middleware/Request.php(73): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#72 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#73 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#74 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#75 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
            "#76 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#77 /Users/danaldridge/Sites/pxcms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(86): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#78 /Users/danaldridge/Sites/pxcms/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#79 {main}"
        ]
    }

}
```

The route in question is registered
```php
// profiles
$router->group(['prefix' => 'u/{auth_user}', 'namespace' => 'ControlPanel'], function (Router $router) {
    $router->get('/', ['as' => 'pxcms.user.view', 'uses' => 'DashboardController@getProfile']);
});
```

and just to make sure laravel see's it..
```
 $ art route:list | grep pxcms.user.view
```
 Domain | Method                         | URI                                                              | Name                      | Action                                                                                  | Middleware                                  
--------|--------------------------------|------------------------------------------------------------------|---------------------------|-----------------------------------------------------------------------------------------|---------------------------------------------
        | GET/HEAD                       | u/{auth_user}                                                    | pxcms.user.view   |         Cms\Modules\Auth\Http\Controllers\Frontend\ControlPanel\DashboardController@getProfile  |

**Comment by jasonlewis** [comment]
So you're saying you can't access regular routes when you have API routes registered? The API shouldn't touch the regular routes at all. If they aren't registered with the API router then they won't be executed by the API.

**Comment by xLink** [comment]
all im doing there is calling `route('pxcms.user.view', $model->id)` as a transformer, so i can reference `['links']['self']` in the array, but it doesn't look like while im in an api route, i can resolve anything that got registered by the regular router

**Comment by jasonlewis** [comment]
Okay I'll take a look, cheers.

**Comment by jasonlewis** [comment]
Just did a very quick test and it seems to be working fine here. Have you run `composer update` recently, because the day before you opened this issue I pushed a fix that merges the routes in with the regular routes.

Are they by any change the same URI with the same domain/prefix (that shouldn't be possible)?

**Comment by xLink** [comment]
i've just done another composer update, to which nothing for api got updated, double checked my routing etc, 

even went as far as to copy the functionality to a route registered normally, and that seemed to work properly :/

**Comment by jasonlewis** [comment]
What commit is your copy of Dingo\Api up to? You should be on at least f1b2fb32fe4aaa81cf96ce7a2b5de288395e1af8.

**Comment by xLink** [comment]
bah yeah i was on https://github.com/dingo/api/commit/b7dead2cd388428af9d4d8463a82d676482b0d5b for some reason composer wouldnt get the newer versions, removal of the composer lock & vendor directory solved that problem.

Which looks like it solved this issue too :D

**Comment by jasonlewis** [comment]
Excellent. Yeah sometimes a stale cache isn't busted by Composer.
