### ISSUE TITLE
Pagination and Query Builder 

### ISSUE THREAD

**Issue by rlacerda83** [dingo/api#580]
Hello again!

I think paging is not working with Query Builder.

My code:

```
$emails = new Email();
$qb = DB::table($emails->getTable());
$qb->where('id', '>', 1);
$paginator = $qb->paginate(5);
$paginator->appends(app('request')->except('page'));
return $this->response->paginator($paginator, new EmailTransformer);
```

Error:

```
{
  "message": "call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Support\Collection' does not have a method 'load'",
  "status_code": 500,
  "debug": {
    "line": 475,
    "file": "/var/www/projects/ecommerce/service-email/vendor/illuminate/pagination/AbstractPaginator.php",
    "class": "ErrorException",
    "trace": [
      "#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(2, 'call_user_func_...', '/var/www/projec...', 475, Array)",
      "#1 /var/www/projects/ecommerce/service-email/vendor/illuminate/pagination/AbstractPaginator.php(475): call_user_func_array(Array, Array)",
      "#2 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Transformer/Adapter/Fractal.php(92): Illuminate\Pagination\AbstractPaginator->__call('load', Array)",
      "#3 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Transformer/Adapter/Fractal.php(92): Illuminate\Pagination\LengthAwarePaginator->load(Array)",
      "#4 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Transformer/Factory.php(85): Dingo\Api\Transformer\Adapter\Fractal->transform(Object(Illuminate\Pagination\LengthAwarePaginator), Object(App\Transformers\EmailTransformer), Object(Dingo\Api\Transformer\Binding), Object(Dingo\Api\Http\Request))",
      "#5 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Http/Response.php(95): Dingo\Api\Transformer\Factory->transform(Object(Illuminate\Pagination\LengthAwarePaginator))",
      "#6 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Routing/Router.php(565): Dingo\Api\Http\Response->morph('json')",
      "#7 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Routing/Router.php(535): Dingo\Api\Routing\Router->prepareResponse(Object(Dingo\Api\Http\Response), Object(Dingo\Api\Http\Request), 'json')",
      "#8 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Http/Middleware/Request.php(93): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
      "#9 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))",
      "#10 /var/www/projects/ecommerce/service-email/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#12 /var/www/projects/ecommerce/service-email/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#13 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Http/Middleware/Request.php(94): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#14 /var/www/projects/ecommerce/service-email/vendor/dingo/api/src/Http/Middleware/Request.php(75): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))",
      "#15 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))",
      "#16 /var/www/projects/ecommerce/service-email/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))",
      "#18 /var/www/projects/ecommerce/service-email/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
      "#19 /var/www/projects/ecommerce/service-email/vendor/laravel/lumen-framework/src/Application.php(1387): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#20 /var/www/projects/ecommerce/service-email/vendor/laravel/lumen-framework/src/Application.php(1164): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))",
      "#21 /var/www/projects/ecommerce/service-email/vendor/laravel/lumen-framework/src/Application.php(1104): Laravel\Lumen\Application->dispatch(NULL)",
      "#22 /var/www/projects/ecommerce/service-email/public/index.php(28): Laravel\Lumen\Application->run()",
      "#23 /var/www/projects/ecommerce/service-email/server.php(12): require_once('/var/www/projec...')",
      "#24 {main}"
    ]
  }
}
```

**Comment by rlacerda83** [comment]
The problem is here:

```
dingo/api/src/Transformer/Adapter/Fractal.php(92)
public function transform($response, $transformer, Binding $binding, Request $request)
    {
        $this->parseFractalIncludes($request);
        $resource = $this->createResource($response, $transformer, $binding->getParameters());
        // If the response is a paginator then we'll create a new paginator
        // adapter for Laravel and set the paginator instance on our
        // collection resource.
        if ($response instanceof IlluminatePaginator) {
            $paginator = $this->createPaginatorAdapter($response);
            $resource->setPaginator($paginator);
        }
        if (($response instanceof EloquentCollection || $response instanceof IlluminatePaginator) && $this->eagerLoading) {
            $eagerLoads = $this->mergeEagerLoads($transformer, $this->fractal->getRequestedIncludes());
            $response->load($eagerLoads);
        }
        foreach ($binding->getMeta() as $key => $value) {
            $resource->setMetaValue($key, $value);
        }
        $binding->fireCallback($resource, $this->fractal);
        return $this->fractal->createData($resource)->toArray();
    }
```
When I use the query builder , the returned object is of type support collection , and this class does not have the load method .

This method only exists in eloquent collection class.

for now, i changes the function to this:
```
 - if (($response instanceof EloquentCollection || $response instanceof IlluminatePaginator) && $this->eagerLoading) {
+ if ($response instanceof EloquentCollection && $this->eagerLoading) {
```

Does anyone have any solution without touching the package ?

tkhs!

**Comment by jasonlewis** [comment]
Working on a fix now. :smile:

**Comment by jasonlewis** [comment]
Fixed.
