### ISSUE TITLE
array_combine(): Both parameters should have an equal number of elements

### ISSUE THREAD

**Issue by nayzawoo** [dingo/api#586]
```
[2015-08-17 21:34:29] local.ERROR: exception 'ErrorException' with message 'array_combine(): Both parameters should have an equal number of elements' in /var/www/html/zawgyimart/vendor/dingo/api/src/Http/Parser/Accept.php:72
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_combine()...', '/var/www/html/z...', 72, Array)
#1 /var/www/html/zawgyimart/vendor/dingo/api/src/Http/Parser/Accept.php(72): array_combine(Array, Array)
#2 /var/www/html/zawgyimart/vendor/dingo/api/src/Http/Validation/Accept.php(53): Dingo\Api\Http\Parser\Accept->parse(Object(Illuminate\Http\Request), false)
#3 /var/www/html/zawgyimart/vendor/dingo/api/src/Http/RequestValidator.php(99): Dingo\Api\Http\Validation\Accept->validate(Object(Illuminate\Http\Request))
#4 /var/www/html/zawgyimart/vendor/dingo/api/src/Http/Middleware/Request.php(70): Dingo\Api\Http\RequestValidator->validateRequest(Object(Illuminate\Http\Request))
#5 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /var/www/html/zawgyimart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/html/zawgyimart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/www/html/zawgyimart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 /var/www/html/zawgyimart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#11 /var/www/html/zawgyimart/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#12 {main}  
```

**Comment by SimonWang2014** [comment]
oh, I have the same error. how to solve?

**Comment by billycris101** [comment]
whats the solution for this one?? have same error

**Comment by mariano-aguero** [comment]
Why the issue was closed?
