### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting

### ISSUE THREAD

**Issue by tienkhoi** [dingo/api#592]
I keep getting this message when trying to get
```
$this->user()
``` 
In controller construct
```
    public function __construct()
    {
        $this->middleware('api.auth');

      
dd($this->user());
    }
```

I'm using 
```
    "dingo/api": "0.10.*",
    "laravel/framework": "5.1.*",
```
With Basic Authentication.

And It shows like this in the log
```

[2015-08-19 20:28:20] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum function nesting level of '100' reached, aborting!' in /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php:687
Stack trace:
#0 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct('', '', '', '', '', '', '', '')
#1 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError('', '')
#2 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(660): Illuminate\Container\Container->getContextualConcrete('')
#4 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(620): Illuminate\Container\Container->getConcrete('')
#5 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('', '')
#6 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(837): Illuminate\Foundation\Application->make('', '')
#7 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->resolveClass('')
#8 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Container\Container->getDependencies('', '')
#9 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('', '')
#10 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('', '')
#11 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(837): Illuminate\Foundation\Application->make('', '')
#12 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->resolveClass('')
#13 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Container\Container->getDependencies('', '')
#14 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('', '')
#15 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('', '')
#16 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(335): Illuminate\Foundation\Application->make('', '')
#17 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(147): Dingo\Api\Routing\Route->makeController()
#18 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(132): Dingo\Api\Routing\Route->setupRoute('', '')
#19 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Router.php(648): Dingo\Api\Routing\Route->__construct('', '', '', '')
#20 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Router.php(626): Dingo\Api\Routing\Router->createRoute('')
#21 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(82): Dingo\Api\Routing\Router->getCurrentRoute()
#22 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(151): Dingo\Api\Auth\Auth->authenticate('')
#23 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(166): Dingo\Api\Auth\Auth->getUser('')
#24 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Helpers.php(141): Dingo\Api\Auth\Auth->user('')
#25 /home/vagrant/Projects/calendarP/app/Http/Controllers/API/AppointmentAPIController.php(35): App\Http\Controllers\API\AppointmentAPIController->user()
#26 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): App\Http\Controllers\API\AppointmentAPIController->__construct('', '')
#27 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): ReflectionClass->newInstanceArgs('')
#28 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('', '')
#29 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('', '')
#30 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(335): Illuminate\Foundation\Application->make('', '')
#31 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(147): Dingo\Api\Routing\Route->makeController()
#32 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(132): Dingo\Api\Routing\Route->setupRoute('', '')
#33 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Router.php(648): Dingo\Api\Routing\Route->__construct('', '', '', '')
#34 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Router.php(626): Dingo\Api\Routing\Router->createRoute('')
#35 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(82): Dingo\Api\Routing\Router->getCurrentRoute()
#36 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(151): Dingo\Api\Auth\Auth->authenticate('')
#37 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(166): Dingo\Api\Auth\Auth->getUser('')
#38 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Helpers.php(141): Dingo\Api\Auth\Auth->user('')
#39 /home/vagrant/Projects/calendarP/app/Http/Controllers/API/AppointmentAPIController.php(35): App\Http\Controllers\API\AppointmentAPIController->user()
#40 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): App\Http\Controllers\API\AppointmentAPIController->__construct('', '')
#41 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): ReflectionClass->newInstanceArgs('')
#42 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('', '')
#43 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('', '')
#44 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(335): Illuminate\Foundation\Application->make('', '')
#45 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(147): Dingo\Api\Routing\Route->makeController()
#46 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Route.php(132): Dingo\Api\Routing\Route->setupRoute('', '')
#47 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Router.php(648): Dingo\Api\Routing\Route->__construct('', '', '', '')
#48 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Router.php(626): Dingo\Api\Routing\Router->createRoute('')
#49 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(82): Dingo\Api\Routing\Router->getCurrentRoute()
#50 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(151): Dingo\Api\Auth\Auth->authenticate('')
#51 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Auth/Auth.php(166): Dingo\Api\Auth\Auth->getUser('')
#52 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Helpers.php(141): Dingo\Api\Auth\Auth->user('')
#53 /home/vagrant/Projects/calendarP/app/Http/Controllers/API/AppointmentAPIController.php(35): App\Http\Controllers\API\AppointmentAPIController->user()
#54 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): App\Http\Controllers\API\AppointmentAPIController->__construct('', '')
#55 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): ReflectionClass->newInstanceArgs('')
#56 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('', '')
#57 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('', '')
#58 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(85): Illuminate\Foundation\Application->make('', '')
#59 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(57): Illuminate\Routing\ControllerDispatcher->makeController('')
#60 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Routing/Route.php(201): Illuminate\Routing\ControllerDispatcher->dispatch('', '', '', '')
#61 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher('')
#62 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Routing\Route->run('')
#63 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Routing\Router->Illuminate\Routing\{closure}('')
#64 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}('', '')
#65 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('')
#66 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}('', '')
#67 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then('')
#68 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack('', '')
#69 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute('')
#70 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch('')
#71 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Routing/Router.php(526): Dingo\Api\Routing\Adapter\Laravel->dispatch('', '')
#72 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Http/Middleware/Request.php(93): Dingo\Api\Routing\Router->dispatch('')
#73 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}('')
#74 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}('', '')
#75 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('')
#76 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\View\Middleware\ShareErrorsFromSession->handle('', '')
#77 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('', '')
#78 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('')
#79 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Session\Middleware\StartSession->handle('', '')
#80 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('', '')
#81 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('')
#82 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle('', '')
#83 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('', '')
#84 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('')
#85 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Cookie\Middleware\EncryptCookies->handle('', '')
#86 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('', '')
#87 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('')
#88 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle('', '')
#89 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('', '')
#90 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('')
#91 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}('', '')
#92 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Http/Middleware/Request.php(94): Illuminate\Pipeline\Pipeline->then('')
#93 /home/vagrant/Projects/calendarP/vendor/dingo/api/src/Http/Middleware/Request.php(75): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter('')
#94 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Dingo\Api\Http\Middleware\Request->handle('', '')
#95 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('', '')
#96 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('')
#97 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}('', '')
#98 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then('')
#99 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter('')
#100 /home/vagrant/Projects/calendarP/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle('')
#101 /home/vagrant/Projects/calendarP/public/index.php(0): {main}()
#102 {main}  
``` 
Could any one help.
Thank you

**Comment by jasonlewis** [comment]
I just pushed a change that will allow this.

Originally it was too early in the cycle as the controller needed to be properly instantiated first. The fix changes that so that it won't try to instantiate the controller too early. Try a `composer update` and let me know how things go.

**Comment by tienkhoi** [comment]
@jasonlewis Thank you for your help, It does work with basic authentication. 
However, when I add 
```
  'jwt' => function ($app) {
            return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
        }
```
into auth array. It backs to the infinity loop. I'm not sure whether the issue is caused from this repo or from JWT.

It will be helpful if you can provide me some more info. 

Thank you again
```

[2015-08-20 23:50:15] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum function nesting level of '100' reached, aborting!' in /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:562
Stack trace:
#0 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Support/Arr.php(153): call_user_func:{/home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Support/Arr.php:153}()
#4 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(564): Illuminate\Support\Arr::first()
#5 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(520): Illuminate\Foundation\Application->getProvider()
#6 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(648): Illuminate\Foundation\Application->register()
#7 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(628): Illuminate\Foundation\Application->registerDeferredProvider()
#8 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(671): Illuminate\Foundation\Application->loadDeferredProvider()
#9 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#10 /home/vagrant/Projects/testingPro/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php(163): Illuminate\Container\Container->offsetGet()
#11 /home/vagrant/Projects/testingPro/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php(260): Illuminate\Foundation\Bootstrap\LoadConfiguration->{closure:/home/vagrant/Projects/testingPro/config/jwt.php:162-164}()
#12 /home/vagrant/Projects/testingPro/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php(260): call_user_func:{/home/vagrant/Projects/testingPro/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php:260}()
#13 /home/vagrant/Projects/testingPro/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php(149): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->getConfigInstance()
#14 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(274): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()
#15 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->Illuminate\Container\{closure}()
#16 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#17 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#18 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#19 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(204): Illuminate\Container\Container->offsetGet()
#20 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(274): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()
#21 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->Illuminate\Container\{closure}()
#22 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#23 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#24 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#25 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(172): Illuminate\Container\Container->offsetGet()
#26 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(274): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()
#27 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->Illuminate\Container\{closure}()
#28 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#29 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#30 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#31 /home/vagrant/Projects/testingPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(188): Illuminate\Container\Container->offsetGet()
```

**Comment by tienkhoi** [comment]
@jasonlewis 
Actually in the middle when I change to
```
        $this->middleware('jwt.auth');
```
It works fine.

Im just not sure whether I should use jwt.auth or api.auth since in the DOC it said api.auth. 

Thank you

**Comment by tienkhoi** [comment]
@jasonlewis I think using api.auth is correct

The part that has issue is 
```
            return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
```
in 
```
   'auth' => [
        'basic' => function ($app) {
            return new Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');
        },
        'jwt' => function ($app) {
            return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);

        }
    ],
```

That makes the forever loop

**Comment by jasonlewis** [comment]
I'll take a look. For now just don't use `user()` in the constructor. There's really no need anyway as you can grab the authenticated user in the methods.

**Comment by tienkhoi** [comment]
I also reported an issue in JWT repository 
```
https://github.com/tymondesigns/jwt-auth/issues/220
```
Seems like this line has some issues with IoC
```
$app['Tymon\JWTAuth\JWTAuth']
```

Not sure how to fix it.

**Comment by sakibfarid** [comment]
I have the same issue when using basic auth and doing an internal request.
In my controller I have the following...

```
$user = $request->user();        
$brands = $this->api()->be($user)->get('api/brands');
```

When I remove the basic auth it works fine.

**Comment by jasonlewis** [comment]
Very late.

But I'm unable to replicate on the latest version of both packages.
