### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by mrgodhani** [dingo/api#611]
```
{"message":"Call to undefined method Closure::authenticate()","code":1,"status_code":500,"debug":{"line":82,"file":"\/vagrant\/crowdlinkersource\/vendor\/dingo\/api\/src\/Auth\/Auth.php","class":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","trace":["#0 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Bootstrap\/HandleExceptions.php(133): Symfony\\Component\\Debug\\Exception\\FatalErrorException->__construct()","#1 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Bootstrap\/HandleExceptions.php(118): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->fatalExceptionFromError()","#2 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Bootstrap\/HandleExceptions.php(0): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()","#3 \/vagrant\/crowdlinkersource\/vendor\/dingo\/api\/src\/Http\/Middleware\/Auth.php(50): Dingo\\Api\\Auth\\Auth->authenticate()","#4 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Dingo\\Api\\Http\\Middleware\\Auth->handle()","#5 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#6 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#7 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): call_user_func:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:103}()","#8 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(706): Illuminate\\Pipeline\\Pipeline->then()","#9 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(671): Illuminate\\Routing\\Router->runRouteWithinStack()","#10 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(631): Illuminate\\Routing\\Router->dispatchToRoute()","#11 \/vagrant\/crowdlinkersource\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Laravel.php(65): Illuminate\\Routing\\Router->dispatch()","#12 \/vagrant\/crowdlinkersource\/vendor\/dingo\/api\/src\/Routing\/Router.php(530): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch()","#13 \/vagrant\/crowdlinkersource\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(110): Dingo\\Api\\Routing\\Router->dispatch()","#14 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(139): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}()","#15 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(139): call_user_func:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:139}()","#16 \/vagrant\/crowdlinkersource\/vendor\/barryvdh\/laravel-cors\/src\/HandleCors.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#17 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Barryvdh\\Cors\\HandleCors->handle()","#18 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#19 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/VerifyCsrfToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#20 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()","#21 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#22 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/View\/Middleware\/ShareErrorsFromSession.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#23 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()","#24 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#25 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#26 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Illuminate\\Session\\Middleware\\StartSession->handle()","#27 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#28 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#29 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()","#30 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#31 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/EncryptCookies.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#32 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()","#33 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#34 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/CheckForMaintenanceMode.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#35 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()","#36 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#37 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#38 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): call_user_func:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:103}()","#39 \/vagrant\/crowdlinkersource\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(111): Illuminate\\Pipeline\\Pipeline->then()","#40 \/vagrant\/crowdlinkersource\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(89): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter()","#41 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): Dingo\\Api\\Http\\Middleware\\Request->handle()","#42 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(124): call_user_func_array:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:124}()","#43 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#44 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): call_user_func:{\/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:103}()","#45 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(122): Illuminate\\Pipeline\\Pipeline->then()","#46 \/vagrant\/crowdlinkersource\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(87): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()","#47 \/vagrant\/crowdlinkersource\/public\/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()","#48 \/vagrant\/crowdlinkersource\/public\/index.php(0): {main}()","#49 {main}"]}}
```

Hi I am getting this error suddenly as above. How to resolve this?

**Comment by kylestev** [comment]
I am getting this as well on the dev build.

**Comment by athad** [comment]
Tracked it down to this change in ApiServiceProvider.php:
```
-        if (is_callable($instance)) {
-            return call_user_func($instance, $this->app);
-        } elseif (is_string($instance)) {
+        if (is_string($instance)) {
```

Reverting to the previous version of the file solved it. I don't know too much about Dingo's internals so I don't know whether what I did was right or wrong :)

**Comment by jasonlewis** [comment]
You'll need to update your config files. Due to how Laravel caches config
files we're no longer allowing anonymous functions in config.

**Comment by athad** [comment]
Got it; basically, I changed the authentication providers according to the new instructions in the Wiki:
`'jwt' => 'Dingo\Api\Auth\Provider\JWT'`

Thanks, Jason!

**Comment by punitgodhani** [comment]
So doing that fixes the error ?

**Comment by mrgodhani** [comment]
@athad did that fix the error issue?

**Comment by mrgodhani** [comment]
Updating config file solves this issue as per new Wiki. Thanks.

**Comment by argb** [comment]
I have the same issue ,but use this 'jwt' => 'Dingo\Api\Auth\Provider\JWT' ,have another bug, "Maximum function nesting level of '100' reached, aborting!","code":1,"status_code":500,

**Comment by omahm** [comment]
@argb I had to set ini_set('xdebug.max_nesting_level', 120); in laravel's bootstrap/autoload.php to get fix the max nesting issue.

**Comment by argb** [comment]
@omahm I tried,don't work,even it work,It can't fundamentally solve the bug. It must there are some big bug in Dingo API.
