### ISSUE TITLE
cant get jwt auth to work

### ISSUE THREAD

**Issue by lein00** [dingo/api#675]
api.php config
    'auth' => [
        'jwt' => 'Dingo\Api\Auth\Provider\JWT'
    ]

routes.php
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', ['prefix' => 'api'], function($api) {
$api->post('auth/login','App\Api\v1\Controllers\AuthController@authenticate');
}

AuthController
use App\User;
use Illuminate\Http\Request;
use Tymon\JWTAuth\Exceptions\JWTException;
use JWTAuth;
class AuthController extends BaseController
{
    public function authenticate(Request $request)
    {
        $credentials = $request->only('email','password');
        try{
            if(!$token = JWTAuth::attempt($credentials)) //its failing on this line
            {
                return response()->json(['error' => 'invalid credentials'],401);
            }
        }
        catch(JWTException $e)
        {
            return response()->json(['error' => 'could not create token'],500);
        }
        return response()->json(compact('$token'));
    }
}
i havent made any changes to the jwt.php config aside from setting the secret key
 im using the User model laravel ships with
my database PostgreSQL
 
any help is appreciated 
TIA
im using POSTMAN to send POST request
the error im getting is
<pre>
{
  "message": "Maximum function nesting level of '100' reached, aborting!",
  "code": 1,
  "status_code": 500,
  "debug": {
    "line": 3,
    "file": "C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Contracts\Cache\Factory.php",
    "class": "Symfony\Component\Debug\Exception\FatalErrorException",
    "trace": [
      "#0 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()",
      "#1 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()",
      "#2 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()",
      "#3 C:\wamp\www\laravel\coed2\vendor\composer\ClassLoader.php(301): Composer\Autoload\includeFile()",
      "#4 C:\wamp\www\laravel\coed2\vendor\composer\ClassLoader.php(0): Composer\Autoload\ClassLoader->loadClass()",
      "#5 C:\wamp\www\laravel\coed2\vendor\composer\ClassLoader.php(12): spl_autoload_call()",
      "#6 C:\wamp\www\laravel\coed2\vendor\composer\ClassLoader.php(412): ()",
      "#7 C:\wamp\www\laravel\coed2\vendor\composer\ClassLoader.php(301): Composer\Autoload\includeFile()",
      "#8 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(0): Composer\Autoload\ClassLoader->loadClass()",
      "#9 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(26): spl_autoload_call()",
      "#10 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): Illuminate\Cache\CacheServiceProvider->Illuminate\Cache\{closure}()",
      "#11 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build()",
      "#12 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make()",
      "#13 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(1159): Illuminate\Foundation\Application->make()",
      "#14 C:\wamp\www\laravel\coed2\vendor\tymon\jwt-auth\src\Providers\JWTAuthServiceProvider.php(163): Illuminate\Container\Container->offsetGet()",
      "#15 C:\wamp\www\laravel\coed2\vendor\tymon\jwt-auth\src\Providers\JWTAuthServiceProvider.php(260): Illuminate\Foundation\Bootstrap\LoadConfiguration->{closure:C:\wamp\www\laravel\coed2\config\jwt.php:162-164}()",
      "#16 C:\wamp\www\laravel\coed2\vendor\tymon\jwt-auth\src\Providers\JWTAuthServiceProvider.php(260): call_user_func:{C:\wamp\www\laravel\coed2\vendor\tymon\jwt-auth\src\Providers\JWTAuthServiceProvider.php:260}()",
      "#17 C:\wamp\www\laravel\coed2\vendor\tymon\jwt-auth\src\Providers\JWTAuthServiceProvider.php(149): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->getConfigInstance()",
      "#18 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(275): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()",
      "#19 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): Illuminate\Container\Container->Illuminate\Container\{closure}()",
      "#20 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build()",
      "#21 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make()",
      "#22 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(1159): Illuminate\Foundation\Application->make()",
      "#23 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(204): Illuminate\Container\Container->offsetGet()",
      "#24 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(275): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()",
      "#25 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): Illuminate\Container\Container->Illuminate\Container\{closure}()",
      "#26 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build()",
      "#27 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make()",
      "#28 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(1159): Illuminate\Foundation\Application->make()",
      "#29 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(172): Illuminate\Container\Container->offsetGet()",
      "#30 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(275): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()",
      "#31 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): Illuminate\Container\Container->Illuminate\Container\{closure}()",
      "#32 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build()",
      "#33 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make()",
      "#34 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(1159): Illuminate\Foundation\Application->make()",
      "#35 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(188): Illuminate\Container\Container->offsetGet()",
      "#36 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(275): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()",
      "#37 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): Illuminate\Container\Container->Illuminate\Container\{closure}()",
      "#38 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build()",
      "#39 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make()",
      "#40 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Container\Container.php(1159): Illuminate\Foundation\Application->make()",
      "#41 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(149): Illuminate\Container\Container->offsetGet()",
      "#42 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(118): Illuminate\Support\Facades\Facade::resolveFacadeInstance()",
      "#43 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Support\Facades\Facade::getFacadeRoot()",
      "#44 C:\wamp\www\laravel\coed2\app\Api\v1\Controllers\AuthController.php(19): Illuminate\Support\Facades\Facade::__callStatic()",
      "#45 C:\wamp\www\laravel\coed2\app\Api\v1\Controllers\AuthController.php(19): Tymon\JWTAuth\Facades\JWTAuth::attempt()",
      "#46 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): App\Api\v1\Controllers\AuthController->authenticate()",
      "#47 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:256}()",
      "#48 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction()",
      "#49 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call()",
      "#50 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()",
      "#51 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()",
      "#52 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#53 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()",
      "#54 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then()",
      "#55 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack()",
      "#56 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Route.php(201): Illuminate\Routing\ControllerDispatcher->dispatch()",
      "#57 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher()",
      "#58 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Router.php(704): Illuminate\Routing\Route->run()",
      "#59 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Illuminate\Routing\Router->Illuminate\Routing\{closure}()",
      "#60 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()",
      "#61 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#62 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()",
      "#63 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Router.php(706): Illuminate\Pipeline\Pipeline->then()",
      "#64 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Router.php(671): Illuminate\Routing\Router->runRouteWithinStack()",
      "#65 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Routing\Router.php(631): Illuminate\Routing\Router->dispatchToRoute()",
      "#66 C:\wamp\www\laravel\coed2\vendor\dingo\api\src\Routing\Adapter\Laravel.php(65): Illuminate\Routing\Router->dispatch()",
      "#67 C:\wamp\www\laravel\coed2\vendor\dingo\api\src\Routing\Router.php(561): Dingo\Api\Routing\Adapter\Laravel->dispatch()",
      "#68 C:\wamp\www\laravel\coed2\vendor\dingo\api\src\Http\Middleware\Request.php(110): Dingo\Api\Routing\Router->dispatch()",
      "#69 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}()",
      "#70 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()",
      "#71 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#72 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()",
      "#73 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()",
      "#74 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#75 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\View\Middleware\ShareErrorsFromSession->handle()",
      "#76 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()",
      "#77 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#78 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Session\Middleware\StartSession->handle()",
      "#79 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()",
      "#80 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#81 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()",
      "#82 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()",
      "#83 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#84 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Cookie\Middleware\EncryptCookies->handle()",
      "#85 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()",
      "#86 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#87 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()",
      "#88 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()",
      "#89 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#90 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()",
      "#91 C:\wamp\www\laravel\coed2\vendor\dingo\api\src\Http\Middleware\Request.php(111): Illuminate\Pipeline\Pipeline->then()",
      "#92 C:\wamp\www\laravel\coed2\vendor\dingo\api\src\Http\Middleware\Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter()",
      "#93 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Dingo\Api\Http\Middleware\Request->handle()",
      "#94 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()",
      "#95 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#96 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()",
      "#97 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then()",
      "#98 C:\wamp\www\laravel\coed2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()",
      "#99 C:\wamp\www\laravel\coed2\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle()",
      "#100 C:\wamp\www\laravel\coed2\index.php(21): ()",
      "#101 C:\wamp\www\laravel\coed2\index.php(0): {main}()",
      "#102 {main}"
    ]
  }
}
</pre>

**Comment by deepslux** [comment]
+1
I am also having this issue. Anyone could help?

<code>
FatalErrorException in Container.php line 172:
Maximum function nesting level of '100' reached, aborting!

in Container.php line 172
at FatalErrorException->__construct() in HandleExceptions.php line 133
at HandleExceptions->fatalExceptionFromError() in HandleExceptions.php line 118
at HandleExceptions->handleShutdown() in HandleExceptions.php line 0
at Container->bind() in Container.php line 257
at Container->singleton() in CacheServiceProvider.php line 49
at CacheServiceProvider->registerCommands() in CacheServiceProvider.php line 37
at CacheServiceProvider->register() in Application.php line 531
at Application->register() in Application.php line 648
at Application->registerDeferredProvider() in Application.php line 628
at Application->loadDeferredProvider() in Application.php line 671
at Application->make() in Container.php line 1159
at Container->offsetGet() in JWTAuthServiceProvider.php line 163
at LoadConfiguration->{closure:C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\config\jwt.php:162-164}() in JWTAuthServiceProvider.php line 260
at call_user_func:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\tymon\jwt-auth\src\Providers\JWTAuthServiceProvider.php:260}() in JWTAuthServiceProvider.php line 260
at JWTAuthServiceProvider->getConfigInstance() in JWTAuthServiceProvider.php line 149
at JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}() in Container.php line 275
at Container->Illuminate\Container\{closure}() in Container.php line 734
at Container->build() in Container.php line 627
at Container->make() in Application.php line 674
at Application->make() in Container.php line 1159
at Container->offsetGet() in Container.php line 204
at JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}() in Container.php line 275
at Container->Illuminate\Container\{closure}() in Container.php line 734
at Container->build() in Container.php line 627
at Container->make() in Application.php line 674
at Application->make() in Container.php line 1159
at Container->offsetGet() in Container.php line 172
at JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}() in Container.php line 275
at Container->Illuminate\Container\{closure}() in Container.php line 734
at Container->build() in Container.php line 627
at Container->make() in Application.php line 674
at Application->make() in Container.php line 1159
at Container->offsetGet() in Container.php line 188
at JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}() in Container.php line 275
at Container->Illuminate\Container\{closure}() in Container.php line 734
at Container->build() in Container.php line 627
at Container->make() in Application.php line 674
at Application->make() in Container.php line 1159
at Container->offsetGet() in Facade.php line 149
at Facade::resolveFacadeInstance() in Facade.php line 118
at Facade::getFacadeRoot() in Facade.php line 203
at Facade::__callStatic() in BaseModel.php line 36
at JWTAuth::parseToken() in BaseModel.php line 36
at BaseModel::user() in BaseModel.php line 48
at BaseModel::App\Models\Shared\{closure}() in Dispatcher.php line 221
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php:221}() in Dispatcher.php line 221
at Dispatcher->fire() in Dispatcher.php line 164
at Dispatcher->until() in Model.php line 1694
at Model->fireModelEvent() in Model.php line 1498
at Model->save() in Model.php line 546
at Model::create() in User.php line 32
at User::register() in UserController.php line 10
at UserController->postRegister() in Controller.php line 256
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:256}() in Controller.php line 256
at Controller->callAction() in ControllerDispatcher.php line 164
at ControllerDispatcher->call() in ControllerDispatcher.php line 112
at ControllerDispatcher->Illuminate\Routing\{closure}() in Pipeline.php line 139
at call_user_func:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}() in Pipeline.php line 139
at Pipeline->Illuminate\Pipeline\{closure}() in Pipeline.php line 103
at call_user_func:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}() in Pipeline.php line 103
at Pipeline->then() in ControllerDispatcher.php line 114
at ControllerDispatcher->callWithinStack() in ControllerDispatcher.php line 69
at ControllerDispatcher->dispatch() in Route.php line 201
at Route->runWithCustomDispatcher() in Route.php line 134
at Route->run() in Router.php line 704
at Router->Illuminate\Routing\{closure}() in Pipeline.php line 139
at call_user_func:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}() in Pipeline.php line 139
at Pipeline->Illuminate\Pipeline\{closure}() in Pipeline.php line 103
at call_user_func:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}() in Pipeline.php line 103
at Pipeline->then() in Router.php line 706
at Router->runRouteWithinStack() in Router.php line 671
at Router->dispatchToRoute() in Router.php line 631
at Router->dispatch() in Kernel.php line 236
at Kernel->Illuminate\Foundation\Http\{closure}() in Pipeline.php line 139
at call_user_func:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}() in Pipeline.php line 139
at Pipeline->Illuminate\Pipeline\{closure}() in Locale.php line 19
at Locale->handle() in Pipeline.php line 124
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}() in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle() in Pipeline.php line 124
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}() in StartSession.php line 62
at StartSession->handle() in Pipeline.php line 124
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}() in ApiSession.php line 14
at ApiSession->handle() in Pipeline.php line 124
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}() in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle() in Pipeline.php line 124
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}() in EncryptCookies.php line 59
at EncryptCookies->handle() in Pipeline.php line 124
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}() in CheckForMaintenanceMode.php line 42
at CheckForMaintenanceMode->handle() in Pipeline.php line 124
at call_user_func_array:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}() in Pipeline.php line 103
at call_user_func:{C:\Users\Nelly\Dropbox\Joint Investment\Home Tutors\Mobile\tutellapi2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}() in Pipeline.php line 103
at Pipeline->then() in Kernel.php line 122
at Kernel->sendRequestThroughRouter() in Kernel.php line 87
at Kernel->handle() in index.php line 54
at {main}() in index.php line 0
</code>

**Comment by rowino** [comment]
Try setting:
```php

'auth' => [
        'jwt' => function ($app) {
            return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
        }
    ],

```

**Comment by lein00** [comment]
@rowino 
tried that same error

**Comment by argb** [comment]
I have the same problem,but why?

**Comment by jasonlewis** [comment]
If you're using the latest version of this package you can't use closures in configuration. You'd need to register it from within a service provider (boot method).

```php
$this->app['api.auth']->extend('jwt', function ($app) {
    return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
});
```

I personally don't use the `0.5.*` version of JWT anymore, I use the development version which is `0.6.*@dev`. Perhaps try upgrading. Note that the docs probably aren't up to date for the package and it's quite a bit different to `0.5.*`.

**Comment by tymondesigns** [comment]
Yep, I'm slacking on the docs.. Gonna go flat out towards the end of this week, to get the news docs done. 

Would be good to coincide `0.6`with `1.0.0` stable of dingo/api. amirite @jasonlewis :)
