### ISSUE TITLE
Unresolvable dependency error when getting user 

### ISSUE THREAD

**Issue by brazenvoid** [dingo/api#686]
I have upgraded to 5.1 and the API works as it should except that I can't get the user from app('\\Dingo\\APi\\Auth\\Auth')->user(). It throws the following exception;

```
{
  "message": "Unresolvable dependency resolving [Parameter #2 [ <required> array $providers ]] in class Dingo\Api\Auth\Auth",
  "status_code": 500,
  "debug": {
    "line": 823,
    "file": "D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Container\Container.php",
    "class": "Illuminate\Contracts\Container\BindingResolutionException",
    "trace": [
      "#0 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Container\Container.php(798): Illuminate\Container\Container->resolveNonClass(Object(ReflectionParameter))",
      "#1 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Container\Container.php(771): Illuminate\Container\Container->getDependencies(Array, Array)",
      "#2 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Container\Container.php(626): Illuminate\Container\Container->build('\\Dingo\\Api\\Auth...', Array)",
      "#3 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('\\Dingo\\Api\\Auth...', Array)",
      "#4 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(54): Illuminate\Foundation\Application->make('\\Dingo\\Api\\Auth...', Array)",
      "#5 D:\Swaggable\swaggable_v3\app\Http\Controllers\Api\BaseController.php(26): app('\\Dingo\\Api\\Auth...')",
      "#6 [internal function]: api\controllers\BaseController->__construct()",
      "#7 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Container\Container.php(775): ReflectionClass->newInstanceArgs(Array)",
      "#8 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Container\Container.php(626): Illuminate\Container\Container->build('api\\controllers...', Array)",
      "#9 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('api\\controllers...', Array)",
      "#10 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Routing\Route.php(335): Illuminate\Foundation\Application->make('api\\controllers...')",
      "#11 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Routing\Route.php(147): Dingo\Api\Routing\Route->makeController()",
      "#12 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Routing\Route.php(132): Dingo\Api\Routing\Route->setupRoute(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))",
      "#13 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Routing\Router.php(648): Dingo\Api\Routing\Route->__construct(Object(Dingo\Api\Routing\Adapter\Laravel), Object(Illuminate\Foundation\Application), Object(Dingo\Api\Http\Request), Object(Illuminate\Routing\Route))",
      "#14 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Routing\Router.php(626): Dingo\Api\Routing\Router->createRoute(Object(Illuminate\Routing\Route))",
      "#15 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Http\Middleware\Auth.php(47): Dingo\Api\Routing\Router->getCurrentRoute()",
      "#16 [internal function]: Dingo\Api\Http\Middleware\Auth->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#17 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#19 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#20 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Routing\Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#21 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Routing\Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))",
      "#22 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Routing\Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))",
      "#23 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Routing\Adapter\Laravel.php(65): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
      "#24 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Routing\Router.php(526): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v3')",
      "#25 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Http\Middleware\Request.php(93): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
      "#26 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))",
      "#27 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#28 D:\Swaggable\swaggable_v3\app\Http\Middleware\VerifyCsrfToken.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#29 [internal function]: swaggable\Http\Middleware\VerifyCsrfToken->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#30 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#31 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#32 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#33 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#34 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#35 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#36 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#37 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#38 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#39 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#40 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#41 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#42 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#43 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#44 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#45 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#47 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#48 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Http\Middleware\Request.php(94): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#49 D:\Swaggable\swaggable_v3\vendor\dingo\api\src\Http\Middleware\Request.php(75): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))",
      "#50 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))",
      "#51 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))",
      "#53 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
      "#54 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#55 D:\Swaggable\swaggable_v3\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))",
      "#56 D:\Swaggable\swaggable_v3\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))",
      "#57 {main}"
    ]
  }
}
```

I then have to again query the database to get the user which requires two extra queries and thus is not optimal.

I have a custom authentication provider setup which works on an existing generated key for each eligible user. There are three kinds of users which can have the key and thus three different models can be returned by the authentication function. That works splendidly. Please help.

**Comment by jasonlewis** [comment]
Going to need a little more context here mate. Where exactly are you calling this method? What does your auth provider look like? And why do you need to query the database again?

**Comment by immense055** [comment]
I have same problem to viewing nice miner site.I can't see my investment and can't make any withdrawal

**Comment by specialtactics** [comment]
@immense055 this issue is very old, if you have a problem (similar or otherwise), please make a new issue, making sure to use the issue template.
