### ISSUE TITLE
OAuth2 authenticate failed.

### ISSUE THREAD

**Issue by dongkaipo** [dingo/api#710]
### install
```
composer create-project laravel/laravel --prefer-dist

chmod -R 777 storage
```
### success

return laravel hello world

### install
```
file: composer.json add

"lucadegasperi/oauth2-server-laravel": "5.0.*"

composer update
```
```
file: config/app.php

providers:
LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider::class,
LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider::class,

aliases:
'Authorizer' => LucaDegasperi\OAuth2Server\Facades\Authorizer::class,


```
```
file: app/Http/Kernel.php

$middleware:
\LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware::class
(remove)App\Http\Middleware\VerifyCsrfToken

$routeMiddleware:
'oauth' => \LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware::class,
'oauth-user' => \LucaDegasperi\OAuth2Server\Middleware\OAuthUserOwnerMiddleware::class,
'oauth-client' => \LucaDegasperi\OAuth2Server\Middleware\OAuthClientOwnerMiddleware::class,
'check-authorization-params' => \LucaDegasperi\OAuth2Server\Middleware\CheckAuthCodeRequestMiddleware::class,
'csrf' => \App\Http\Middleware\VerifyCsrfToken::class,
```
```
php artisan vendor:publish

php artisan migrate
```

### configure
```
file: config/oauth2.php

'grant_types' => [
    'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => '\App\Http\Controllers\Auth\PasswordGrantVerifier@verify',
            'access_token_ttl' => 3600
        ]
]

```
```
file: app/Http/Controller/Auth/PasswordGrantVerifier.php

namespace App\Http\Controllers\Auth;
use Illuminate\Support\Facades\Auth;

class PasswordGrantVerifier
{
  public function verify($username, $password)
  {
      $credentials = [
        'email'    => $username,
        'password' => $password,
      ];

      if (Auth::once($credentials)) {
          return Auth::user()->id;
      }

      return false;
  }
}

```
```
table:oauth_clients

id:1 secret:123 name:test

table:users

id:1 name:Jack email:jack@laravel.com password:Hash::make('password')
```
```
file: app/Http/routes.php

Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});
```
### success

```
post: api.laravel.app/oauth/access_token
grant_type:password
client_id:1
client_secret:123
password:password
username:jack@laravel.com

return:
{
  "access_token": "9CavxbvJ8sa1lrfLKbUlHd8QfjS1idUanH7jpVdd",
  "token_type": "Bearer",
  "expires_in": 3600
}
```

```
file: app/Http/routes.php
Route::get('user', ['middleware' => 'oauth', function() {
    return 'hello world';
}]);
```
```
get: api.laravel.app/user

header: Authorization: Bearer 9CavxbvJ8sa1lrfLKbUlHd8QfjS1idUanH7jpVdd

return :
hello world
```

### install
```
file: composer.json
"require": {
    "dingo/api": "1.0.*@dev"
}

composer update
```
```
file: config/app.php
'providers' => [
    Dingo\Api\Provider\LaravelServiceProvider::class
]
```

### configure

```
php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"
```
```
file:.env

API_STANDARDS_TREE=vnd
API_SUBTYPE=laravel
API_DOMAIN=api.laravel.app
API_NAME=Laravel API
API_CONDITIONAL_REQUEST=false
API_STRICT=true
API_DEFAULT_FORMAT=json
API_DEBUG=true

```
```
file: app/Http/routes.php

$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {
    $api->get('/dingo',function(){
        return "hello world";
    });
});
```
```
file: app/Http/Controllers/Controller.php

use Dingo\Api\Routing\Helpers;

use Helpers;

```
### success
```
get: /dingo
header: Accept:application/vnd.laravel.v1+json

return:
hello world 
```

### configure
```
php artisan make:provider OAuthServiceProvider

namespace App\Providers;

use Dingo\Api\Auth\Auth;
use Dingo\Api\Auth\Provider\OAuth2;
use Illuminate\Support\ServiceProvider;

class OAuthServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->app[Auth::class]->extend('oauth', function ($app) {
            $provider = new OAuth2($app['oauth2-server.authorizer']->getChecker());

            $provider->setUserResolver(function ($id) {
                // Logic to return a user by their ID.
            });

            $provider->setClientResolver(function ($id) {
                // Logic to return a client by their ID.
            });

            return $provider;
        });
    }

    public function register()
    {
        //
    }
}
```
```
file: app/Http/Controllers/Auth/OAuthController.php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use Exception;
use LucaDegasperi\OAuth2Server\Authorizer;

/**
 * @property mixed response
 */
class OAuthController extends Controller{
    protected $authorizer;

    public function __construct(Authorizer $authorizer){
        $this->authorizer = $authorizer;
    }

    public function accessToken() {
        try {
            return $this->authorizer->issueAccessToken();
        }catch (Exception $e) {
            return $this->response->errorUnauthorized('认证失败');
        }
    }

}
```
```
file: app/Http/routes.php

$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {

    $api->post('user/access_token','App\Http\Controllers\Auth\OAuthController@accessToken');

    $api->get('/no_access',function(){
        return "no_access";
    });

    $api->group(['middleware' => 'api.auth'],function($api){
        $api->get('my',function(){
            return 'oauth my';
        });
    });
});


```

### success
```
post: /user/access_token
header: Accept:application/vnd.laravel.v1+json
body:
grant_type:password
client_id:1
client_secret:123
password:password
username:jack@laravel.com

return:
{
  "access_token": "NRXfLpfH0AonXsyICKbwV3lFsGI2acIOmC5xm9tT",
  "token_type": "Bearer",
  "expires_in": 3600
}

```
```
get: /no_access
header:Accept:application/vnd.laravel.v1+json

return:
no_access
```

### failed (always)
```
get: /my
header:
Accept:application/vnd.laravel.v1+json
Authorization:Bearer NRXfLpfH0AonXsyICKbwV3lFsGI2acIOmC5xm9tT

return: 
{
  "message": "Failed to authenticate because of bad credentials or an invalid authorization header.",
  "status_code": 401
 }
```

if i modify `config/api.php` `'auth'` to 

```
'auth' => [
        'oauth'=> function($app) {
            $provider = new Dingo\Api\Auth\Provider\OAuth2($app['oauth2-server.authorizer']->getChecker());

            $provider->setUserResolver(function ($id) {
                // Logic to return a user by their ID.
            });

            $provider->setClientResolver(function ($id) {
                // Logic to return a client by their ID.
            });

            return $provider;
        }
    ],
```

return error

```
{
  "message": "Call to undefined method Closure::authenticate()",
  "code": 1,
  "status_code": 500,
  "debug": {
    "line": 82,
    "file": "/home/vagrant/Code/laravel/vendor/dingo/api/src/Auth/Auth.php",
    "class": "Symfony\Component\Debug\Exception\FatalErrorException",
    "trace": [
      "#0 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()",
      "#1 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()",
      "#2 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()",
      "#3 /home/vagrant/Code/laravel/vendor/dingo/api/src/Http/Middleware/Auth.php(50): Dingo\Api\Auth\Auth->authenticate()",
      "#4 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Dingo\Api\Http\Middleware\Auth->handle()",
      "#5 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()",
      "#6 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#7 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()",
      "#8 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then()",
      "#9 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack()",
      "#10 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute()",
      "#11 /home/vagrant/Code/laravel/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch()",
      "#12 /home/vagrant/Code/laravel/vendor/dingo/api/src/Routing/Router.php(561): Dingo\Api\Routing\Adapter\Laravel->dispatch()",
      "#13 /home/vagrant/Code/laravel/vendor/dingo/api/src/Http/Middleware/Request.php(110): Dingo\Api\Routing\Router->dispatch()",
      "#14 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}()",
      "#15 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}()",
      "#16 /home/vagrant/Code/laravel/vendor/lucadegasperi/oauth2-server-laravel/src/Middleware/OAuthExceptionHandlerMiddleware.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#17 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware->handle()",
      "#18 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()",
      "#19 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#20 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\View\Middleware\ShareErrorsFromSession->handle()",
      "#21 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()",
      "#22 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#23 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Session\Middleware\StartSession->handle()",
      "#24 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()",
      "#25 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#26 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()",
      "#27 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()",
      "#28 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#29 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Cookie\Middleware\EncryptCookies->handle()",
      "#30 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()",
      "#31 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#32 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()",
      "#33 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()",
      "#34 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#35 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()",
      "#36 /home/vagrant/Code/laravel/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\Pipeline\Pipeline->then()",
      "#37 /home/vagrant/Code/laravel/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter()",
      "#38 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Dingo\Api\Http\Middleware\Request->handle()",
      "#39 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()",
      "#40 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()",
      "#41 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()",
      "#42 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then()",
      "#43 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()",
      "#44 /home/vagrant/Code/laravel/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle()",
      "#45 /home/vagrant/Code/laravel/public/index.php(0): {main}()",
      "#46 {main}"
    ]
  }
}
```

That all my configure . Dingo work well and oauth2 work well and getting token success by dingo.But not work for authenticating by dingo.

Where are the errors ? ORZ...

Thanks~ :)

**Comment by dongkaipo** [comment]
And you can found it https://github.com/dongkaipo/Laravel-OAuth2-Dingo

**Comment by dongkaipo** [comment]
file:config/app.php

`"providers"` add `App\Providers\OAuthServiceProvider::class,`

**Comment by tulsidaskhatri** [comment]
@dongkaipo could you resolve the issue? I am stuck with exactly same thing.
