### ISSUE TITLE
Basic Auth fails with PHPUnit

### ISSUE THREAD

**Issue by jinseokoh** [dingo/api#720]
I can't make basic.auth work when testing with PHPUnit. It fails with 401 "Invalid authentication credentials."

    .Dingo\Api\Http\Response {#625
      #binding: null
      +original: array:3 [
        "message" => "Invalid authentication credentials."
        "status_code" => 401
        "debug" => array:4 [
          "line" => 55
          "file" => "/home/vagrant/sites/joara2/vendor/dingo/api/src/Auth/Provider/Basic.php"
          "class" => "Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException"
          "trace" => array:56 [
            0 => "#0 /home/vagrant/sites/joara2/vendor/dingo/api/src/Auth/Auth.php(82): Dingo\Api\Auth\Provider\Basic->authenticate(Object(Dingo\Api\Http\Request), Object(Dingo\Api\Routing\Route))"
            1 => "#1 /home/vagrant/sites/joara2/vendor/dingo/api/src/Http/Middleware/Auth.php(50): Dingo\Api\Auth\Auth->authenticate(Array)"
            2 => "#2 [internal function]: Dingo\Api\Http\Middleware\Auth->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
            3 => "#3 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)"
            4 => "#4 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            5 => "#5 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))"
            6 => "#6 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))"
            7 => "#7 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))"
            8 => "#8 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))"
            9 => "#9 /home/vagrant/sites/joara2/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))"
            10 => "#10 /home/vagrant/sites/joara2/vendor/dingo/api/src/Routing/Router.php(530): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')"
            11 => "#11 /home/vagrant/sites/joara2/vendor/dingo/api/src/Http/Middleware/Request.php(110): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))"
            12 => "#12 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))"
            13 => "#13 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))"
            14 => "#14 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            15 => "#15 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
            16 => "#16 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)"
            17 => "#17 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            18 => "#18 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
            19 => "#19 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)"
            20 => "#20 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            21 => "#21 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
            22 => "#22 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)"
            23 => "#23 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            24 => "#24 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
            25 => "#25 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)"
            26 => "#26 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            27 => "#27 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
            28 => "#28 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)"
            29 => "#29 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            30 => "#30 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
            31 => "#31 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)"
            32 => "#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            33 => "#33 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))"
            34 => "#34 /home/vagrant/sites/joara2/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))"
            35 => "#35 /home/vagrant/sites/joara2/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))"
            36 => "#36 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))"
            37 => "#37 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)"
            38 => "#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))"
            39 => "#39 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))"
            40 => "#40 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))"
            41 => "#41 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))"
            42 => "#42 /home/vagrant/sites/joara2/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php(393): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))"
            43 => "#43 /home/vagrant/sites/joara2/tests/NovelTest.php(274): Illuminate\Foundation\Testing\TestCase->call('POST', '/v1/books/novel', Array, Array, Array, Array)"
            44 => "#44 [internal function]: NovelTest->post_novel_with_photo()"
            45 => "#45 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/Framework/TestCase.php(909): ReflectionMethod->invokeArgs(Object(NovelTest), Array)"
            46 => "#46 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/Framework/TestCase.php(768): PHPUnit_Framework_TestCase->runTest()"
            47 => "#47 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/Framework/TestResult.php(612): PHPUnit_Framework_TestCase->runBare()"
            48 => "#48 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/Framework/TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(NovelTest))"
            49 => "#49 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/Framework/TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))"
            50 => "#50 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/Framework/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))"
            51 => "#51 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))"
            52 => "#52 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/TextUI/Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)"
            53 => "#53 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit_TextUI_Command->run(Array, true)"
            54 => "#54 /home/vagrant/sites/joara2/vendor/phpunit/phpunit/phpunit(47): PHPUnit_TextUI_Command::main()"
            55 => "#55 {main}"
          ]
        ]
      ]

My API still works fine when testing with Postman. Anyone have any clues?

config/api.php

    <?php

    return [
        :
        'version' => 'v1',
        'prefix' => 'v1',
        'domain' => null,
        'name' => 'MyAPI',
        'strict' => false,
        'debug' => true,
        :
    ];

AppServiceProvider.php

    <?php

    namespace App\Providers;

    use Illuminate\Support\ServiceProvider;
    use Dingo\Api\Auth\Provider\Basic;

    class AppServiceProvider extends ServiceProvider
    {
        public function boot()
        {
            $this->app['api.auth']->extend('basic', function ($app) {
                return new Basic($app['auth'], 'email');
            });

        }
        :
    }

routes.php

    $api->version('v1', [ 'namespace' => 'App\Http\Controllers' ], function($api) {
        $api->group([ 'middleware' => 'api.auth' ], function($api) {

            /* users */
            $api->get('users',               [ 'as' => 'users.index',         'uses' => 'UserController@index' ]);
            $api->get('users/{id}',          [ 'as' => 'users.show',          'uses' => 'UserController@show' ]);
            $api->post('users',              [ 'as' => 'users.store',         'uses' => 'UserController@create' ]);
        });
    });

UserTest.php

    /**
     * @test
     */
    public function get_all_users()
    {

            $header = [ 'HTTP_Authorization' => 'Basic cXVlZW5Aam9hcmEuY29tOnRlc3Q=' ];
            $this->get('/v1/users', $header)->seeStatusCode(200);
    }

**Comment by jinseokoh** [comment]
couldn't make it work with basic.auth but, was able to work with jwt auth instead. so i'm closing this.
