### ISSUE TITLE
500 Error Class not found when syntax error is present

### ISSUE THREAD

**Issue by OwenMelbz** [dingo/api#836]
Hi, new to both laravel and dingo, I managed to spend several hours today stuck on something that seemed very stupid, and cannot figure out how to make it work as expected.

So I was getting a 500 Error JSON response, that said

```json
{
    message: "Class App\Http\Controllers\BotlistController does not exist",
    status_code: 500,
    debug: {
    line: 264,
    file: "/home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
    class: "ReflectionException",
       trace: [
"#0 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): ReflectionMethod->__construct('App\\Http\\Contro...', 'index')",
"#1 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(838): Illuminate\Routing\Route->signatureParameters('Illuminate\\Data...')",
"#2 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(823): Illuminate\Routing\Router->substituteImplicitBindings(Object(Illuminate\Routing\Route))",
"#3 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Router->substituteBindings(Object(Illuminate\Routing\Route))",
"#4 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->findRoute(Object(Dingo\Api\Http\Request))",
"#5 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))",
"#6 /home/vagrant/selesti-api/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
"#7 /home/vagrant/selesti-api/vendor/dingo/api/src/Routing/Router.php(559): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')",
"#8 /home/vagrant/selesti-api/vendor/dingo/api/src/Http/Middleware/Request.php(110): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
"#9 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))",
"#10 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
"#11 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#12 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
"#13 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
"#15 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
"#16 /home/vagrant/selesti-api/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
"#17 /home/vagrant/selesti-api/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))",
"#18 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
"#19 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
"#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))",
"#21 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
"#22 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))",
"#23 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
"#24 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
"#25 /home/vagrant/selesti-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))",
"#26 /home/vagrant/selesti-api/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))",
"#27 {main}"
]
}
}
```

So this was saying the controller was not found, however the actual error was below

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class LegacyTwitterController extends Controller
{
    public $this->username = null;

```

So the actual error was the fact I don't a bad copy/paste, So the error it should have shown me was something like this

```php
      Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';' in app/Http/Controllers/LegacyTwitterController.php on line 12

Errors parsing app/Http/Controllers/LegacyTwitterController.php
  ```

However I then spent an hour or so debugging routes. 

Why is this showing an incorrect error? and how can we work around to give it the actual error as I feel this is going to cause hell every time there is a mistake and it wont tell you without jumping into the terminal and doing something like `php -l app/Http/Controllers/TwitterController.php`

Would appreciate the guidance as to what is going on here.

Many thanks

**Comment by 73sl4** [comment]
Hi,

You shouldn't use $this while initialising a property in class.

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class LegacyTwitterController extends Controller
{
    public $username = null; // Remove $this
```

It'll work fine after this.

**Comment by OwenMelbz** [comment]
No I know that, thats not the issue, that was just because I copied pasted something.

The problem is why was the correct error not thrown, you can type `bananas` there for all it matters, but the syntax error isnt shown, just a 404

**Comment by jasonlewis** [comment]
What does the `LegacyTwitterController` have to do with the `BotlistController` not being found?

**Comment by OwenMelbz** [comment]
Sorry I was demoing the issue to a collegue on a controller that was working (botlist) and copy/pasted the wrong stack trace, but the issue still stands

**Comment by jasonlewis** [comment]
So what's the issue exactly? You've pasted the wrong stack trace so can I see the actual stack trace?

I've tested with a bunch of different syntax errors and I'm seeing the correct error being reported.
