### ISSUE TITLE
Updating Dingo broke my app.

### ISSUE THREAD

**Issue by morfin** [dingo/api#877]
Before updating I was using 3062aac and everything worked fine.

After update to latest commit (53502e1), My app started giving me this error:

```
"Undefined property: Illuminate\Http\JsonResponse::$exception"

0: "#0 /home/vagrant/laravel_app/vendor/dingo/api/src/Routing/Router.php(561): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/home/vagrant/l...', 561, Array)"
1: "#1 /home/vagrant/laravel_app/vendor/dingo/api/src/Http/Middleware/Request.php(112): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))"
2: "#2 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))"
3: "#3 /home/vagrant/laravel_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))"
4: "#4 /home/vagrant/laravel_app/vendor/barryvdh/laravel-cors/src/HandleCors.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
5: "#5 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
.....
```

Any idea?

**Comment by jasonlewis** [comment]
#875.

Don't use `JsonResponse`.
