### ISSUE TITLE
lumen 'php artisan optimize'

### ISSUE THREAD

**Issue by 0plus1** [dingo/api#901]
Results in this error:

```
php artisan optimize
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #1 [ <required> array $format ]] in class Dingo\Api\Exception\Handler' in /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:828
Stack trace:
#0 /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php(803): Illuminate\Container\Container->resolveNonClass(Object(ReflectionParameter))
#1 /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php(776): Illuminate\Container\Container->getDependencies(Array, Array)
#2 /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('App\\Exceptions\\...', Array)
#3 /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php(447): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.p in /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php on line 828

Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #1 [ <required> array $format ]] in class Dingo\Api\Exception\Handler' in /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php on line 828

Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #1 [ <required> array $format ]] in class Dingo\Api\Exception\Handler in /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php on line 828

Call Stack:
    1.2331   11428768   1. Laravel\Lumen\Application->Laravel\Lumen\{closure}() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:0
    1.2331   11428920   2. Laravel\Lumen\Application->handleUncaughtException() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:341
    1.2331   11428968   3. Laravel\Lumen\Application->make() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:397
    1.2331   11429104   4. Illuminate\Container\Container->make() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:447
    1.2331   11429104   5. Illuminate\Container\Container->build() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:631
    1.2331   11429104   6. Illuminate\Container\Container->Illuminate\Container\{closure}() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:738
    1.2331   11429152   7. Laravel\Lumen\Application->make() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:220
    1.2331   11429152   8. Illuminate\Container\Container->make() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:447
    1.2331   11429152   9. Illuminate\Container\Container->build() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:631
    1.2332   11431184  10. Illuminate\Container\Container->getDependencies() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:776
    1.2332   11432064  11. Illuminate\Container\Container->resolveNonClass() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:803

PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #1 [ <required> array $format ]] in class Dingo\Api\Exception\Handler' in /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:828
Stack trace:
#0 /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php(803): Illuminate\Container\Container->resolveNonClass(Object(ReflectionParameter))
#1 /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php(776): Illuminate\Container\Container->getDependencies(Array, Array)
#2 /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('App\\Exceptions\\...', Array)
#3 /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php(447): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.p in /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php on line 828

Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #1 [ <required> array $format ]] in class Dingo\Api\Exception\Handler' in /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php on line 828

Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #1 [ <required> array $format ]] in class Dingo\Api\Exception\Handler in /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php on line 828

Call Stack:
    1.2374   11458320   1. Laravel\Lumen\Application->Laravel\Lumen\{closure}() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:0
    1.2420   11493912   2. Laravel\Lumen\Application->handleUncaughtException() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:348
    1.2420   11493960   3. Laravel\Lumen\Application->make() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:397
    1.2420   11494096   4. Illuminate\Container\Container->make() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:447
    1.2420   11494096   5. Illuminate\Container\Container->build() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:631
    1.2420   11494096   6. Illuminate\Container\Container->Illuminate\Container\{closure}() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:738
    1.2420   11494144   7. Laravel\Lumen\Application->make() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:220
    1.2420   11494144   8. Illuminate\Container\Container->make() /home/vagrant/Code/leaderbird.co/api/vendor/laravel/lumen-framework/src/Application.php:447
    1.2420   11494144   9. Illuminate\Container\Container->build() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:631
    1.2420   11496176  10. Illuminate\Container\Container->getDependencies() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:776
    1.2421   11497056  11. Illuminate\Container\Container->resolveNonClass() /home/vagrant/Code/leaderbird.co/api/vendor/illuminate/container/Container.php:803```

**Comment by jasonlewis** [comment]
Lumen has an `optimize` command?

Anyhow, what version is Dingo on? Have you upgraded recently?

**Comment by 0plus1** [comment]
According to my composer.lock:

```"name": "dingo/api",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/dingo/api.git",
                "reference": "b36db17c7294e44e6ce7039952ca8f8d57caab37"
            },```

**Comment by jasonlewis** [comment]
That's quite an old commit. Please update.
