### ISSUE TITLE
Class api does not exist

### ISSUE THREAD

**Issue by yaoshanliang** [dingo/api#906]
Version 1.0.x now throws exception `Class api does not exist`

**Comment by jasonlewis** [comment]
And?

Look, that's not a report. You've given me absolutely nothing to go on with this. No proper stack trace. No example code that's causing the issue. No mention of the framework you're using (Laravel/Lumen) or the version of it.

Please report the issue correctly so I can help you resolve it.

**Comment by yaoshanliang** [comment]
I run composer update
```
[
      "#0 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('api')",
      "#1 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('api', Array)",
      "#2 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Illuminate\Container\Container->make('api', Array)",
      "#3 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(123): Illuminate\Foundation\Application->make('api')",
      "#4 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#5 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#6 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))",
      "#7 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#8 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#9 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))",
      "#10 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))",
      "#11 /home/iat/workspace/code/ehs/vendor/dingo/api/src/Routing/Adapter/Laravel.php(56): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
      "#12 /home/iat/workspace/code/ehs/vendor/dingo/api/src/Routing/Router.php(559): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')",
      "#13 /home/iat/workspace/code/ehs/vendor/dingo/api/src/Http/Middleware/Request.php(112): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
      "#14 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))",
      "#15 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#16 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#17 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#18 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#20 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#21 /home/iat/workspace/code/ehs/vendor/dingo/api/src/Http/Middleware/Request.php(113): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#22 /home/iat/workspace/code/ehs/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))",
      "#23 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#24 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))",
      "#26 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
      "#27 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))",
      "#28 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
      "#29 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#30 /home/iat/workspace/code/ehs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))",
      "#31 /home/iat/workspace/code/ehs/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))",
      "#32 {main}"
    ]
```

**Comment by jasonlewis** [comment]
So you're calling what `app('api')` somewhere? That's not a binding.

Show some code. What are you trying to do?
