### ISSUE TITLE
404 only while accessing through another laravel app

### ISSUE THREAD

**Issue by brazenvoid** [dingo/api#909]
I am having this strange dilemma which gets me 404 on all routes of the api when its accessed by laravel through guzzle. While all routes run fine through Postman and browsers.

Here is the trace log by guzzle;

```
stdClass (4) (
    public success -> bool FALSE
    public message -> string (13) "404 Not Found"
    public status_code -> integer 404
    public debug -> stdClass (4) (
        public line -> integer 161
        public file -> string (92) "**********\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php"
        public class -> string (60) "Symfony\Component\HttpKernel\Exception\NotFoundHttpException"
        public trace -> array (25) [
            string (166) "#0 **********\vendor\laravel\framework\src\Illuminate\Routing\Router.php(823): Illuminate\Routing\RouteCollection->match(Object(Dingo\Api\Http\Request))"
            string (161) "#1 **********\vendor\laravel\framework\src\Illuminate\Routing\Router.php(691): Illuminate\Routing\Router->findRoute(Object(Dingo\Api\Http\Request))"
            string (167) "#2 **********\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))"
            string (149) "#3 **********\vendor\dingo\api\src\Routing\Adapter\Laravel.php(56): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))"
            string (155) "#4 **********\vendor\dingo\api\src\Routing\Router.php(559): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')"
            string (149) "#5 **********\vendor\dingo\api\src\Http\Middleware\Request.php(112): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))"
            string (126) "#6 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))"
            string (159) "#7 **********\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))"
            string (219) "#8 **********\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            string (142) "#9 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))"
            string (131) "#10 **********\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)"
            string (116) "#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))"
            string (160) "#12 **********\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))"
            string (135) "#13 **********\vendor\dingo\api\src\Http\Middleware\Request.php(113): Illuminate\Pipeline\Pipeline->then(Object(Closure))"
            string (174) "#14 **********\vendor\dingo\api\src\Http\Middleware\Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))"
            string (116) "#15 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))"
            string (131) "#16 **********\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)"
            string (117) "#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))"
            string (159) "#18 **********\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))"
            string (115) "#19 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))"
            string (161) "#20 **********\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))"
            string (153) "#21 **********\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))"
            string (193) "#22 **********\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))"
            string (125) "#23 **********\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))"
            string (10) "#24 {main}"
        ]
    ))
```

**Route**

```
$this->apiClient = new Client(array(
        'base_uri' => 'http://api.work.com',
        'timeout' => 0,
        'allow_redirects' => true,
        'headers' => array(
            'Accept' => 'x.work.v1+json'
        )
    ));
$this->apiClient->get('users');
```

**Guzzle Settings**

```
$this->apiClient = new Client(array(
        'base_uri' => 'http://api.work.com',
        'timeout' => 0,
        'allow_redirects' => true,
        'headers' => array(
            'Accept' => 'x.work.v1+json'
        )
    ));
$this->apiClient->get('users');
```

I have checked out the regex generated by the Route which essentially doesn't match with the route at all.

Target Route: /users
Regex generated: "#^\/users$#s"

**Comment by brazenvoid** [comment]
I resolved it through not setting the base url in guzzle and removing http prefixes from api domain on both ends. Though the reason to it has alluded me so far.

**Comment by jasonlewis** [comment]
Unsure what the issue could have been. Your route/guzzle settings are the same paste.

Could you debug the request that Guzzle was setting and checking if it all matches up?

Also that regex and route combination looks fine to me, should have been matching.
