### ISSUE TITLE
Controller constructor called twice?

### ISSUE THREAD

**Issue by assembledadam** [dingo/api#922]
Trying to figure this one out. My controller __contruct() method is being called twice by the app.

I've generated a stack trace of both calls, which are different.  The first:

```
#0 [internal function]: App\Http\Controllers\ArticleController->__construct(Object(App\Repositories\ArticleRepository))
#1 /usr/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(783): ReflectionClass->newInstanceArgs(Array)
#2 /usr/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#3 /usr/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#4 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#5 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(52): Illuminate\Routing\ControllerDispatcher->makeController('App\\Http\\Contro...')
#6 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request), 'App\\Http\\Contro...', 'getAll')
#7 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Dingo\Api\Http\Request))
#8 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Dingo\Api\Http\Request))
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#10 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#11 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#12 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#13 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))
#15 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))
#16 /usr/www/app/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#17 /usr/www/app/vendor/dingo/api/src/Routing/Router.php(559): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')
#18 /usr/www/app/vendor/dingo/api/src/Http/Middleware/Request.php(112): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#19 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))
#20 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#21 /usr/www/app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#22 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#23 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#24 /usr/www/app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#25 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#26 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#27 /usr/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#29 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#31 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#32 /usr/www/app/vendor/dingo/api/src/Http/Middleware/Request.php(113): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /usr/www/app/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))
#34 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /usr/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /usr/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#42 /usr/www/app/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#43 {main}
```

The second: 
```
#0 [internal function]: App\Http\Controllers\ArticleController->__construct(Object(App\Repositories\ArticleRepository))
#1 /usr/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(783): ReflectionClass->newInstanceArgs(Array)
#2 /usr/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#3 /usr/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#4 /usr/www/app/vendor/dingo/api/src/Routing/Route.php(327): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#5 /usr/www/app/vendor/dingo/api/src/Routing/Route.php(188): Dingo\Api\Routing\Route->makeControllerInstance()
#6 /usr/www/app/vendor/dingo/api/src/Routing/Route.php(171): Dingo\Api\Routing\Route->mergeControllerProperties()
#7 /usr/www/app/vendor/dingo/api/src/Routing/Route.php(148): Dingo\Api\Routing\Route->setupRouteProperties(Object(Dingo\Api\Http\Request), Object(Illuminate\Routing\Route))
#8 /usr/www/app/vendor/dingo/api/src/Routing/Router.php(696): Dingo\Api\Routing\Route->__construct(Object(Dingo\Api\Routing\Adapter\Laravel), Object(Illuminate\Foundation\Application), Object(Dingo\Api\Http\Request), Object(Illuminate\Routing\Route))
#9 /usr/www/app/vendor/dingo/api/src/Routing/Router.php(674): Dingo\Api\Routing\Router->createRoute(Object(Illuminate\Routing\Route))
#10 /usr/www/app/vendor/dingo/api/src/Routing/Router.php(636): Dingo\Api\Routing\Router->getCurrentRoute()
#11 /usr/www/app/vendor/dingo/api/src/Routing/Router.php(606): Dingo\Api\Routing\Router->requestIsConditional()
#12 /usr/www/app/vendor/dingo/api/src/Routing/Router.php(572): Dingo\Api\Routing\Router->prepareResponse(Object(Dingo\Api\Http\Response), Object(Dingo\Api\Http\Request), 'json')
#13 /usr/www/app/vendor/dingo/api/src/Http/Middleware/Request.php(112): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#14 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))
#15 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#16 /usr/www/app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#17 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#18 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#19 /usr/www/app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#20 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#21 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#22 /usr/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#23 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#24 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#26 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#27 /usr/www/app/vendor/dingo/api/src/Http/Middleware/Request.php(113): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /usr/www/app/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))
#29 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /usr/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /usr/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /usr/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /usr/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#37 /usr/www/app/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#38 {main}
```

Any ideas?

**Comment by jasonlewis** [comment]
What's the context? Hitting a Laravel route? Hitting an API endpoint?

**Comment by assembledadam** [comment]
Sorry - this is hitting an API endpoint.

```
$api = app('Dingo\Api\Routing\Router');

// API App
$api->version('v1', function ($api) {
    APIRoute::get('articles', 'App\\Http\\Controllers\\ArticleController@getAll');
});
```

**Comment by assembledadam** [comment]
Annnd here's your test case: https://github.com/assembledadam/laravel/commit/9f98b776b90ad0766fcb590fae3e1e0f08c8f4e0

Looks to be a specific issue with creating a controller constructor...

The output of this test case, when hitting /test/123, is:
```
"calling base controller constructor"
"getAll() called"
"calling base controller constructor"
```

**Comment by jasonlewis** [comment]
Yeah this was an interesting one. I actually remember this being an issue once before but something must have happened between the Laravel changes.

I've implemented a fix that can be applied across both Laravel & Lumen. It utilizes a new `PrepareController` middleware that is automatically applied to every route added to the API. This simply creates the controller instance and binds it as a singleton prior to Laravel/Lumen instantiating it.

**Comment by assembledadam** [comment]
That's a pretty ingenious solution!  Will give it a go - as always thank you for the speedy resolution. 

After we go into production, and assuming things go ok, I'll be hiring some developers to help me out and further the development of our app/platform - at that point I'll make sure we throw some help your way.  A brilliant package, thanks again.

**Comment by zjien** [comment]
I have the same problem but this issue have solved it,thank you

**Comment by zjien** [comment]
but I want to know why controller will be instantiated twice?

**Comment by assembledadam** [comment]
If you are calling two internal routes on your API, one after the other, the expectation is for them to be entirely compartmentalised - i.e. one should not affect the other. 

So you could end up with unexpected results if you e.g. do any processing on the initialisation of a controller, the output of which changes depending request and it's parameters.

**Comment by aleemb** [comment]
@jasonlewis Is this issue back? Just noticed it in Laravel 5.8 + Dingo 2.3.0.

**Comment by vanushwashere** [comment]
I experience it on Laravel 6 with Dingo 2.4.7
