### ISSUE TITLE
Lumen 5.2 error

### ISSUE THREAD

**Issue by jdforsythe** [dingo/api#931]
The example at https://github.com/0plus1/lumendingojwtapi works perfectly until you update to Lumen 5.2. Then even running `artisan` gives:

```
[InvalidArgumentException]
Auth guard [] is not defined.
```

Commenting out this part of `bootstrap/app.php` is the only thing that stops the error:

```php
app('Dingo\Api\Auth\Auth')->extend('jwt', function ($app) {
    return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
});
```

Stack:

```
[2016-03-23 20:00:45] lumen.ERROR: exception 'InvalidArgumentException' with message 'Auth guard [] is not defined.' in E:\dev\web-services\PayHubAPI\vendor\illuminate\auth\AuthManager.php:86
Stack trace:
#0 E:\dev\web-services\PayHubAPI\vendor\illuminate\auth\AuthManager.php(70): Illuminate\Auth\AuthManager->resolve(NULL)
#1 E:\dev\web-services\PayHubAPI\vendor\illuminate\auth\AuthServiceProvider.php(45): Illuminate\Auth\AuthManager->guard()
#2 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(735): Illuminate\Auth\AuthServiceProvider->Illuminate\Auth\{closure}(Object(Laravel\Lumen\Application), Array)
#3 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#4 E:\dev\web-services\PayHubAPI\vendor\laravel\lumen-framework\src\Application.php(205): Illuminate\Container\Container->make('auth.driver', Array)
#5 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(853): Laravel\Lumen\Application->make('Illuminate\\Cont...')
#6 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#7 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(779): Illuminate\Container\Container->getDependencies(Array, Array)
#8 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(633): Illuminate\Container\Container->build('Tymon\\JWTAuth\\P...', Array)
#9 E:\dev\web-services\PayHubAPI\vendor\laravel\lumen-framework\src\Application.php(205): Illuminate\Container\Container->make('Tymon\\JWTAuth\\P...', Array)
#10 E:\dev\web-services\PayHubAPI\vendor\tymon\jwt-auth\src\Providers\AbstractServiceProvider.php(276): Laravel\Lumen\Application->make('Tymon\\JWTAuth\\P...')
#11 E:\dev\web-services\PayHubAPI\vendor\tymon\jwt-auth\src\Providers\AbstractServiceProvider.php(123): Tymon\JWTAuth\Providers\AbstractServiceProvider->getConfigInstance('providers.auth')
#12 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(735): Tymon\JWTAuth\Providers\AbstractServiceProvider->Tymon\JWTAuth\Providers\{closure}(Object(Laravel\Lumen\Application), Array)
#13 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#14 E:\dev\web-services\PayHubAPI\vendor\laravel\lumen-framework\src\Application.php(205): Illuminate\Container\Container->make('tymon.jwt.provi...', Array)
#15 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(1178): Laravel\Lumen\Application->make('tymon.jwt.provi...')
#16 E:\dev\web-services\PayHubAPI\vendor\tymon\jwt-auth\src\Providers\AbstractServiceProvider.php(192): Illuminate\Container\Container->offsetGet('tymon.jwt.provi...')
#17 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(735): Tymon\JWTAuth\Providers\AbstractServiceProvider->Tymon\JWTAuth\Providers\{closure}(Object(Laravel\Lumen\Application), Array)
#18 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#19 E:\dev\web-services\PayHubAPI\vendor\laravel\lumen-framework\src\Application.php(205): Illuminate\Container\Container->make('tymon.jwt.auth', Array)
#20 E:\dev\web-services\PayHubAPI\vendor\illuminate\container\Container.php(1178): Laravel\Lumen\Application->make('Tymon\\JWTAuth\\J...')
#21 E:\dev\web-services\PayHubAPI\bootstrap\app.php(92): Illuminate\Container\Container->offsetGet('Tymon\\JWTAuth\\J...')
#22 [internal function]: {closure}(Object(Laravel\Lumen\Application))
#23 E:\dev\web-services\PayHubAPI\vendor\dingo\api\src\Auth\Auth.php(216): call_user_func(Object(Closure), Object(Laravel\Lumen\Application))
#24 E:\dev\web-services\PayHubAPI\bootstrap\app.php(93): Dingo\Api\Auth\Auth->extend('jwt', Object(Closure))
#25 E:\dev\web-services\PayHubAPI\artisan(18): require('E:\\dev\\web-serv...')
#26 {main}  
```

**Comment by jdforsythe** [comment]
Closing as I believe this is more related to missing configuration in the example package than a bug.
