### ISSUE TITLE
oauth2 service provider getting error in Laravel 5.2

### ISSUE THREAD

**Issue by lasithg** [dingo/api#951]
Hi, im using Laravel 5.2.27. Everything i configured as described in the documentation and created oAuth service provider for auth
```
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Dingo\Api\Auth\Auth;
use Dingo\Api\Auth\Provider\OAuth2;
use App\Models\User;

class OAuthServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->app[Auth::class]->extend('oauth', function ($app) {

            $provider = new OAuth2($app['oauth2-server.authorizer']->getChecker());

            $provider->setUserResolver(function ($id) {
                return User::find($id);
            });

            $provider->setClientResolver(function ($id) {
                // Logic to return a client by their ID.
            });

            return $provider;
        });
    }

    public function register()
    {
        //
    }
}
```
in my api config file

```
    'auth' => [
        'oauth' => App\Providers\OAuthServiceProvider::class
    ],
```
my .env file
```
API_STANDARDS_TREE=x
API_SUBTYPE=myapp
API_NAME=testapp
API_PREFIX=api
API_VERSION=v1
API_CONDITIONAL_REQUEST=true
API_STRICT=false
API_DEBUG=true
API_DEFAULT_FORMAT=json
```

my route,

```
$api->version('v1', function ($api) {
    
    $api->group(['middleware' => 'api.auth'], function ($api) {
        
        $api->get('user', function () {

            $user = Auth::user();

            return $user;
        });

    });
});
```

when i access this route i getting this error

```
{"message":"Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\\Support\\ServiceProvider","status_code":500,"debug":{
"line":839,
"file":"G:\\wamp\\www\\oacstaffapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php",
"class":"Illuminate\\Contracts\\Container\\BindingResolutionException",
"trace":["#0 G:\\wamp\\www\\oacstaffapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))",
"#1 G:\\wamp\\www\\oacstaffapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)",
"#2 G:\\wamp\\www\\oacstaffapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(633): Illuminate\\Container\\Container->build('App\\\\Providers\\\\O...', Array)",
"#3 G:\\wamp\\www\\oacstaffapp\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(697): Illuminate\\Container\\Container->make('App\\\\Providers\\\\O...', Array)",
"#4 G:\\wamp\\www\\oacstaffapp\\vendor\\dingo\\api\\src\\Provider\\ServiceProvider.php(65): Illuminate\\Foundation\\Application->make('App\\\\Providers\\\\O...')",
"#5 G:\\wamp\\www\\oacstaffapp\\vendor\\dingo\\api\\src\\Provider\\ServiceProvider.php(48): Dingo\\Api\\Provider\\ServiceProvider->instantiateConfigValue('auth', 'App\\\\Providers\\\\O...')",
"#6 G:\\wamp\\www\\oacstaffapp\\vendor\\dingo\\api\\src\\Provider\\ServiceProvider.php(31): Dingo\\Api\\Provider\\ServiceProvider->instantiateConfigValues('auth', Array)",
"#7 G:\\wamp\\www\\oacstaffapp\\vendor\\dingo\\api\\src\\Provider\\DingoServiceProvider.php(155): Dingo\\Api\\Provider\\ServiceProvider->config('auth')","#8 ..................
```

**Comment by jasonlewis** [comment]
You've got a little bit wrong there.

In the API config file you should not be registering the provider, you would register that provider in your `config/app.php` file under the `providers` key, somewhere after the Dingo service provider.
