### ISSUE TITLE
Oauth2 broken with latest Dingo

### ISSUE THREAD

**Issue by ngroot** [dingo/api#982]
I've been running the oauth2 server from https://github.com/lucadegasperi/oauth2-server-laravel version 5.1.4 using the dev-master version of dingo/api.

Lately I ran in a problem in my api it could not get the access token anymore during the request. The complete error from the oauth2 package was:

`NoActiveAccessTokenException Authorizer.php line 104 Tried to access session data without an active access token`

I narrowed it done to be an issue in an update of the dingo/api package. Rolling back to the 1.0.0-beta3 tag solved the problem.

I could not find why this is happening but it looks like route middlewares do not work anymore.

**Comment by jasonlewis** [comment]
Is there any more to the stack trace or is that it?

**Comment by ngroot** [comment]
The oauth middleware is defined like:

```php
$api->group(['middleware' => ['oauth'], 'namespace' => 'App\Http\Controllers'], function ($api) {
}
```

The complete trace of the error

```json
{
  "message": "Tried to access session data without an active access token",
  "error": 1,
  "status_code": 500,
  "debug": {
    "line": 104,
    "file": "/var/www/vhosts/example.com/releases/release-7/vendor/lucadegasperi/oauth2-server-laravel/src/Authorizer.php",
    "class": "LucaDegasperi\\OAuth2Server\\Exceptions\\NoActiveAccessTokenException",
    "trace": [
      "#0 /var/www/vhosts/example.com/releases/release-7/app/ASM/Util/Session.php(26): LucaDegasperi\\OAuth2Server\\Authorizer->getAccessToken()",
      "#1 /var/www/vhosts/example.com/releases/release-7/app/ASM/Util/Session.php(65): App\\ASM\\Util\\Session::getSession()",
      "#2 /var/www/vhosts/example.com/releases/release-7/app/ASM/Util/Session.php(43): App\\ASM\\Util\\Session::getUser()",
      "#3 /var/www/vhosts/example.com/releases/release-7/app/ASM/Util/Session.php(84): App\\ASM\\Util\\Session::getCustomer()",
      "#4 /var/www/vhosts/example.com/releases/release-7/app/Http/Controllers/BaseController.php(32): App\\ASM\\Util\\Session::validateCustomer(Object(App\\ASM\\Models\\Customer))",
      "#5 [internal function]: App\\Http\\Controllers\\BaseController->__construct(Object(Dingo\\Api\\Http\\Request))",
      "#6 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Container/Container.php(783): ReflectionClass->newInstanceArgs(Array)",
      "#7 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...', Array)",
      "#8 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...', Array)",
      "#9 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Route.php(325): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')",
      "#10 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Route.php(186): Dingo\\Api\\Routing\\Route->makeControllerInstance()",
      "#11 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Route.php(167): Dingo\\Api\\Routing\\Route->mergeControllerProperties()",
      "#12 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Route.php(144): Dingo\\Api\\Routing\\Route->setupRouteProperties(Object(Dingo\\Api\\Http\\Request), Object(Illuminate\\Routing\\Route))",
      "#13 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Router.php(713): Dingo\\Api\\Routing\\Route->__construct(Object(Dingo\\Api\\Routing\\Adapter\\Laravel), Object(Illuminate\\Foundation\\Application), Object(Dingo\\Api\\Http\\Request), Object(Illuminate\\Routing\\Route))",
      "#14 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Router.php(691): Dingo\\Api\\Routing\\Router->createRoute(Object(Illuminate\\Routing\\Route))",
      "#15 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Router.php(701): Dingo\\Api\\Routing\\Router->getCurrentRoute()",
      "#16 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Http/Middleware/PrepareController.php(43): Dingo\\Api\\Routing\\Router->current()",
      "#17 [internal function]: Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#18 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#19 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#20 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#21 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#22 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#23 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#24 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
      "#25 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
      "#26 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Adapter/Laravel.php(82): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
      "#27 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Routing/Router.php(574): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
      "#28 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Http/Middleware/Request.php(123): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
      "#29 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#30 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#31 /var/www/vhosts/example.com/releases/release-7/vendor/lucadegasperi/oauth2-server-laravel/src/Middleware/OAuthExceptionHandlerMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#32 [internal function]: LucaDegasperi\\OAuth2Server\\Middleware\\OAuthExceptionHandlerMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#33 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#34 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#35 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#36 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#37 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#38 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#39 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Http/Middleware/Request.php(124): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#40 /var/www/vhosts/example.com/releases/release-7/vendor/dingo/api/src/Http/Middleware/Request.php(100): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
      "#41 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
      "#42 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#43 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
      "#44 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
      "#45 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
      "#46 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
      "#47 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#48 /var/www/vhosts/example.com/releases/release-7/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
      "#49 /var/www/vhosts/example.com/releases/release-7/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
      "#50 {main}"
    ]
  }
}
```

**Comment by ngroot** [comment]
I've scrolled back in my composer.lock history and the last working commit for me was at

https://github.com/dingo/api/commit/7e6dfe2d6fcfa31d6e7681ba6bb60c78d5584efc

Somewhere after that it broke for me.

**Comment by jasonlewis** [comment]
Why are you not using `api.auth`?

**Comment by jasonlewis** [comment]
That said, what is going on in your base controller? What does `App\\ASM\\Util\\Session::validateCustomer` do?

**Comment by jasonlewis** [comment]
Is this during tests or through something like Postman?

**Comment by lukasoppermann** [comment]
Any news here? I am also getting this error on lumen.


If I put this in within the routes function I get the error.

```php
$api->group([
    'version' => 'v1',
    'middleware' => 'api.auth',
], function($api)
{
   dd(app('oauth2-server.authorizer')->hasScope('Tet'));
```

**Comment by lukasoppermann** [comment]
Okay, I got mine working. I don't know what else was wrong, because I tried it before, but in the end I was missing the `valdiateAccessToken` call, which afterwards made the session available. However, IMO the session should already have been available, due to the 'api.auth' middleware on the route group. Maybe there is still a need for a fix?

```php
        $authorizer = app('oauth2-server.authorizer');
        $authorizer->validateAccessToken();
```

**Comment by swilla** [comment]
I'm having the same issue @lukasoppermann  Where did you put the `validateAccessToken` call?

**Comment by lukasoppermann** [comment]
Well I have build a Request class which has an authorize method. You need to call the `validateAccessToken` before you actually need the session, e.g. before you try hasScope. 

```php
$authorizer = app('oauth2-server.authorizer');
$authorizer->validateAccessToken();

if(!app('oauth2-server.authorizer')->hasScope('client.read')){
    return false;
}
```

I think the `api.auth` middleware does the same, and for the the scopes in the _route group_ worked fine, however it seems the auth middleware somehow deletes the session afterwards or the session is restricted to inside the middleware so that you can not get it outside. Is this true @jasonlewis?

**Comment by hskrasek** [comment]
@lukasoppermann @swilla @ngroot Is this still an issue y'all are currently experiencing?

**Comment by ngroot** [comment]
@hskrasek I have no problem anymore :+1:

**Comment by swilla** [comment]
No longer an issue! 👍

**Comment by hskrasek** [comment]
Awesome, closing out
